const STORAGE_KEY='revision-route-state-v3';
const examDate=new Date('2026-10-22T00:00:00');
const DAILY_CHOICE_COUNT=15;
const DAILY_MEMORIZE_COUNT=2;
const syllabusChapters=[
 {id:'art-core',title:'第一章 艺术本质与功能',days:8,summary:'艺术定义、特征、社会功能与艺术分类'},
 {id:'architecture',title:'第二章 建筑艺术专题',days:10,summary:'建筑本质、空间、装饰、材料与结构'},
 {id:'residence',title:'第三章 民居与地域气候',days:8,summary:'气候、地域、传统民居与生活方式'},
 {id:'garden',title:'第四章 园林与宫殿',days:7,summary:'皇家园林、私家园林、宫殿与礼制'},
 {id:'religion',title:'第五章 宗教建筑',days:7,summary:'宗教建筑功能、基督教、伊斯兰教与佛教建筑'},
 {id:'modern',title:'第六章 建筑传承与现代建筑',days:7,summary:'传统建筑传承、现代建筑思想与代表作品'},
 {id:'creation',title:'第七章 艺术创作与作品',days:6,summary:'艺术体验、构思、想象、内容、形式与艺术形象'},
 {id:'appreciation',title:'第八章 艺术鉴赏',days:4,summary:'审美感知、审美体验、审美理解与审美效应'},
 {id:'exam',title:'第九章 真题方向与主观题',days:3,summary:'高频概念、简答题、论述题与综合模拟'}
];
const questionChapter={a1:'art-core',a2:'art-core',a3:'art-core',a4:'creation',a5:'creation',a6:'creation',a7:'creation',a8:'appreciation',a9:'art-core',a10:'art-core',a11:'art-core',a12:'architecture',a13:'architecture',a14:'architecture',a15:'appreciation',a16:'appreciation',a17:'exam',a18:'residence',a19:'residence',a20:'residence',a21:'garden',a22:'garden',a23:'garden',a24:'religion',a25:'religion',a26:'religion',a27:'modern',a28:'modern',a29:'modern',f1:'creation',f2:'creation',f3:'appreciation',f4:'residence',f5:'garden',f6:'religion',f7:'modern',m1:'art-core',m2:'art-core'};

const questionBank=[
 {id:'a1',type:'choice',chapter:'第一章 艺术本质',section:'艺术的本质',q:'艺术的本质，首先可以理解为哪一种活动？',options:['纯粹的娱乐活动','人类以感性形象进行的审美创造和精神生产','对自然物的机械复制','只服务于商业宣传的活动'],answer:1,explain:'艺术不是简单复制，也不只是娱乐，而是人类借助具体形象进行审美创造和精神生产的社会实践。',keywords:'审美创造｜感性形象｜精神生产',memorize:'艺术是人类以感性形象进行审美创造和精神生产的社会实践。'},
 {id:'a2',type:'choice',chapter:'第一章 艺术本质',section:'艺术的社会功能',q:'下列哪一项不属于艺术的主要社会功能？',options:['审美功能','认识功能','教育功能','替代法律裁判功能'],answer:3,explain:'艺术常见功能包括审美、认识、教育和娱乐等，但艺术不能替代法律制度和司法裁判。',keywords:'审美｜认识｜教育｜娱乐',memorize:'艺术的主要社会功能包括审美、认识、教育和娱乐功能。'},
 {id:'a3',type:'choice',chapter:'第一章 艺术本质',section:'艺术分类',q:'按作品存在方式分类，文学、音乐、舞蹈更接近哪一类艺术？',options:['时间艺术','空间艺术','静态造型艺术','实用技术'],answer:0,explain:'文学、音乐、舞蹈都在时间过程中展开和完成，因此属于时间艺术；绘画、雕塑主要属于空间艺术。',keywords:'时间艺术｜空间艺术｜动态展开',memorize:'按存在方式，艺术可分为时间艺术、空间艺术和时空艺术。'},
 {id:'a4',type:'choice',chapter:'第七章 艺术创作与作品',section:'艺术创作',q:'艺术创作过程通常包括哪三个基本阶段？',options:['观察、模仿、销售','艺术体验、艺术构思、艺术表现','选材、印刷、展览','欣赏、批评、收藏'],answer:1,explain:'艺术家先从生活中获得体验，再通过构思形成主题和形象，最后借助媒介把构思表现为作品。',keywords:'体验｜构思｜表现',memorize:'艺术创作通常经历艺术体验、艺术构思和艺术表现三个阶段。'},
 {id:'a5',type:'choice',chapter:'第七章 艺术创作与作品',section:'艺术想象',q:'艺术想象在艺术创作中的核心作用是什么？',options:['完全脱离生活经验','把生活经验进行联想、改造和重组，形成新的艺术形象','只负责选择作品价格','避免使用任何传统素材'],answer:1,explain:'艺术想象以生活经验为基础，通过联想、改造、加工和重组形成新的艺术形象，是艺术创造性的重要来源。',keywords:'生活经验｜联想｜改造｜重组',memorize:'艺术想象是在生活经验基础上进行联想、改造和重组的创造性活动。'},
 {id:'a6',type:'choice',chapter:'第七章 艺术创作与作品',section:'艺术作品',q:'艺术作品的内容与形式是什么关系？',options:['内容和形式互不相关','内容决定一切，形式没有作用','内容与形式相互依存并统一于作品','形式越复杂作品越优秀'],answer:2,explain:'内容规定作品表达的思想和情感方向，形式使内容获得具体、可感的表现，优秀作品追求二者统一。',keywords:'内容｜形式｜统一',memorize:'艺术作品是内容与形式的统一，内容决定表达方向，形式使内容具体可感。'},
 {id:'a7',type:'choice',chapter:'第七章 艺术创作与作品',section:'艺术形象',q:'艺术形象最突出的基本特征是什么？',options:['只有抽象概念，没有具体感受','既有具体可感性和情感性，又具有个性与共性','完全等同于现实照片','只能表现个人情绪'],answer:1,explain:'艺术形象既要具体可感、富有情感，又要通过个别形象反映一定社会生活的普遍意义。',keywords:'具体可感｜情感性｜个性与共性',memorize:'艺术形象具有具体可感性、情感性、个性与共性等特点。'},
 {id:'a8',type:'choice',chapter:'第八章 艺术鉴赏',section:'艺术鉴赏',q:'艺术鉴赏通常经历怎样的心理过程？',options:['感知、体验、理解','购买、收藏、转售','模仿、复制、传播','判断、处罚、执行'],answer:0,explain:'鉴赏者先感知作品的形式和形象，再产生情感体验，最后结合背景和经验形成理解。',keywords:'审美感知｜审美体验｜审美理解',memorize:'艺术鉴赏通常经历审美感知、审美体验和审美理解三个阶段。'},
 {id:'a9',type:'choice',chapter:'第二章 艺术发展',section:'生活与艺术',q:'社会生活与艺术发展的基本关系是什么？',options:['艺术与生活完全无关','社会生活是艺术创作的源泉和基础，艺术又反作用于生活','艺术只能由艺术家凭空创造','生活只能被艺术单向复制'],answer:1,explain:'社会生活提供艺术创作的题材、情感和思想，艺术又通过审美表现影响人的观念和社会文化。',keywords:'生活源泉｜艺术反映｜反作用',memorize:'社会生活是艺术创作的源泉和基础，艺术又反映生活并反作用于生活。'},
 {id:'a10',type:'choice',chapter:'第二章 艺术发展',section:'继承与创新',q:'艺术发展中继承传统与艺术创新的关系应当是？',options:['只继承不创新','只创新不继承','在继承有价值传统的基础上面向时代创新','传统和创新永远对立'],answer:2,explain:'继承保证艺术发展的文化连续性，创新使艺术回应新的生活和审美需要，二者相互促进。',keywords:'继承传统｜面向时代｜创新发展',memorize:'艺术创新不是割断传统，而是在继承传统精华的基础上面向时代发展。'},
 {id:'a11',type:'choice',chapter:'第二章 艺术发展',section:'民族性与世界性',q:'艺术的民族性与世界性是什么关系？',options:['民族性越强，越不可能被理解','世界性就是取消民族特色','民族性是艺术个性的基础，世界性使作品能够跨文化交流','二者没有任何联系'],answer:2,explain:'民族性来自特定民族的历史和生活，世界性来自人类共同的情感和审美经验，二者可以统一。',keywords:'民族土壤｜共同情感｜跨文化交流',memorize:'艺术的民族性是艺术个性的基础，世界性使艺术能够跨文化交流。'},
 {id:'a12',type:'choice',chapter:'第三章 艺术门类',section:'建筑艺术',q:'建筑艺术的科学性和艺术性分别主要解决什么问题？',options:['科学性解决安全、材料、结构和功能；艺术性塑造形态、空间和文化表达','科学性只负责装饰；艺术性只负责承重','科学性和艺术性都只负责外观','建筑没有艺术性'],answer:0,explain:'建筑首先要满足结构安全和使用功能，同时通过造型、空间、比例和文化象征形成审美价值。',keywords:'结构安全｜使用功能｜造型空间｜文化表达',memorize:'建筑的科学性保证安全、材料、结构和功能，艺术性通过造型、空间和文化表达审美。'},
 {id:'a13',type:'choice',chapter:'第三章 艺术门类',section:'造型艺术',q:'绘画、雕塑、摄影通常被归入哪一类艺术？',options:['造型艺术','语言艺术','表演艺术','实用技术'],answer:0,explain:'绘画、雕塑和摄影主要通过可视的形体、色彩和构图塑造艺术形象，属于造型艺术。',keywords:'可视形象｜形体｜色彩｜构图',memorize:'绘画、雕塑、摄影主要通过可视形象塑造艺术形象，属于造型艺术。'},
 {id:'a14',type:'choice',chapter:'第三章 艺术门类',section:'实用与审美',q:'实用艺术最重要的特征是？',options:['只追求美而不考虑使用','在满足实用功能的同时追求审美价值','不能表达文化意义','完全排斥技术和材料'],answer:1,explain:'建筑、工艺美术、设计等实用艺术既服务于生活功能，也通过形式、材料和文化表达产生审美价值。',keywords:'实用功能｜审美价值｜生活服务',memorize:'实用艺术是在满足实用功能的同时追求审美价值的艺术门类。'},
 {id:'a15',type:'choice',chapter:'第四章 艺术鉴赏',section:'审美效应',q:'艺术鉴赏的审美效应不包括哪一项？',options:['情感共鸣','精神净化','思想领悟','强制他人接受同一观点'],answer:3,explain:'艺术鉴赏可以引发共鸣、净化情感、启发思想，但审美接受具有主动性，不能强制统一。',keywords:'情感共鸣｜精神净化｜思想领悟',memorize:'艺术鉴赏的审美效应主要表现为情感共鸣、精神净化和思想领悟。'},
 {id:'a16',type:'choice',chapter:'第五章 艺术传播',section:'艺术接受',q:'艺术鉴赏的主观差异主要来自什么？',options:['每个人看到的作品不同','生活经验、文化修养和审美趣味不同','艺术作品没有客观规律','鉴赏完全不需要作品本身'],answer:1,explain:'不同人的生活经历、文化知识、艺术修养和审美趣味不同，因此会产生差异；但鉴赏仍须以作品和艺术规律为依据。',keywords:'生活经验｜文化修养｜审美趣味',memorize:'艺术鉴赏存在主观差异，但不能脱离作品本身、历史背景和艺术规律。'},
 {id:'a17',type:'choice',chapter:'第五章 艺术传播',section:'美术馆功能',q:'美术馆承担的基本公共文化功能是什么？',options:['只负责出售艺术品','收藏、展示、研究和公共教育','只为少数艺术家提供工作室','替代学校完成全部教育'],answer:1,explain:'美术馆通过收藏、展览、研究和公共教育保存艺术成果，并帮助公众理解和参与艺术。',keywords:'收藏｜展示｜研究｜公共教育',memorize:'美术馆的基本功能包括收藏、展示、研究和公共教育。'},
 {id:'f1',type:'fill',chapter:'第七章 艺术创作与作品',section:'创作过程',q:'艺术创作通常经历艺术____、艺术____和艺术____三个阶段。',options:['体验','构思','表现','销售'],answers:[0,1,2],explain:'艺术家从生活中获得体验，经过构思形成主题和形象，最后通过媒介完成表现。',keywords:'体验｜构思｜表现',memorize:'艺术创作通常经历艺术体验、艺术构思和艺术表现三个阶段。'},
 {id:'f2',type:'fill',chapter:'第七章 艺术创作与作品',section:'内容与形式',q:'艺术作品是____与____的统一。',options:['内容','形式','价格','材料'],answers:[0,1],explain:'内容规定作品表达的思想情感方向，形式使内容获得具体可感的表现。',keywords:'内容｜形式｜统一',memorize:'艺术作品是内容与形式的统一。'},
 {id:'f3',type:'fill',chapter:'第八章 艺术鉴赏',section:'鉴赏过程',q:'艺术鉴赏通常包括审美____、审美____和审美____。',options:['感知','体验','理解','交易'],answers:[0,1,2],explain:'鉴赏先感知形式和形象，再产生情感体验，最后结合经验和背景形成理解。',keywords:'感知｜体验｜理解',memorize:'艺术鉴赏通常包括审美感知、审美体验和审美理解。'},
 {id:'m1',type:'memorize',chapter:'第一章 艺术本质',section:'核心定义',q:'背诵：什么是艺术？',answerText:'艺术是人类以感性形象进行审美创造和精神生产的社会实践。',keywords:'感性形象｜审美创造｜精神生产｜社会实践',explain:'回答时先说艺术的主体是人类，再说方式是感性形象和审美创造，最后落到精神生产和社会实践。'},
 {id:'m2',type:'memorize',chapter:'第二章 艺术发展',section:'继承创新',q:'背诵：如何理解艺术继承与创新的关系？',answerText:'艺术发展需要继承传统精华，同时面向时代生活进行创新；继承保持文化连续性，创新使艺术适应新的生活和审美需要。',keywords:'继承传统｜文化连续性｜面向时代｜创新发展',explain:'答题抓住两层：继承解决“从哪里来”，创新解决“向哪里去”，二者不是割裂而是统一。'},
 {id:'a18',type:'choice',chapter:'第三章 民居与地域气候',section:'气候与建筑',q:'传统民居适应地域气候，最直接的表现是什么？',options:['所有地区采用相同平面','围绕通风、采光、保温和防雨调整空间与构造','只改变建筑名称','完全排斥当地材料'],answer:1,explain:'传统民居会针对温度、降水、风向和日照条件，调整屋顶、墙体、开口与院落，形成适应当地生活的建筑。',keywords:'地域气候｜通风采光｜保温防雨',memorize:'传统民居通过屋顶、墙体、开口和院落等空间构造适应地域气候与生活方式。'},
 {id:'a19',type:'choice',chapter:'第三章 民居与地域气候',section:'北京四合院',q:'北京四合院以院落组织空间，主要体现了什么特点？',options:['向外完全敞开','以中心院落联系各房屋并体现家庭秩序','只用于宗教仪式','建筑之间互不关联'],answer:1,explain:'四合院以院落为中心组织正房、厢房和倒座房，既改善采光通风，也体现传统家庭伦理和内向生活方式。',keywords:'中心院落｜内向布局｜家庭秩序',memorize:'北京四合院以中心院落组织房屋，形成内向布局，并体现传统家庭秩序。'},
 {id:'a20',type:'choice',chapter:'第三章 民居与地域气候',section:'地域材料',q:'传统民居大量使用当地材料的主要原因是什么？',options:['便于取得并适应当地环境与建造技术','为了让各地建筑完全相同','只为增加装饰','当地材料没有实用作用'],answer:0,explain:'当地材料容易获得，运输和建造成本较低，也长期接受当地气候检验，能够形成具有地域特色的构造和外观。',keywords:'就地取材｜环境适应｜地域特色',memorize:'传统民居常就地取材，使材料、构造、气候与地域生活方式相互适应。'},
 {id:'a21',type:'choice',chapter:'第四章 园林与宫殿',section:'中国园林',q:'中国传统园林组织空间时最强调哪种审美追求？',options:['一览无余、完全对称','借景、对景和曲折变化形成自然意趣','只追求建筑高度','取消植物与水体'],answer:1,explain:'中国传统园林通过借景、对景、框景和曲折路径，使有限空间产生层次变化，追求虽由人作、宛自天开的自然意趣。',keywords:'借景｜对景｜空间层次｜自然意趣',memorize:'中国传统园林通过借景、对景和曲折空间营造层次，追求自然意趣。'},
 {id:'a22',type:'choice',chapter:'第四章 园林与宫殿',section:'皇家与私家园林',q:'皇家园林与私家园林相比，皇家园林通常更突出什么？',options:['规模宏大和政治礼制象征','完全没有建筑','只供普通市场交易','空间极小且不使用轴线'],answer:0,explain:'皇家园林服务帝王生活和国家礼制，往往规模宏大、景观类型丰富，并体现权力和秩序；私家园林则更精巧含蓄。',keywords:'规模宏大｜礼制象征｜精巧含蓄',memorize:'皇家园林规模宏大并体现礼制与权力，私家园林多在有限空间中追求精巧含蓄。'},
 {id:'a23',type:'choice',chapter:'第四章 园林与宫殿',section:'宫殿建筑',q:'中国古代宫殿建筑常用中轴对称布局，主要表达什么？',options:['随意与无序','等级、礼制和政治秩序','纯粹模仿自然','取消主次关系'],answer:1,explain:'中轴线组织主要殿堂，两侧建筑对称展开，通过空间主次和尺度差异强化等级与礼制秩序。',keywords:'中轴对称｜主次分明｜礼制秩序',memorize:'古代宫殿常以中轴对称、主次分明的布局体现等级和礼制秩序。'},
 {id:'a24',type:'choice',chapter:'第五章 宗教建筑',section:'宗教建筑功能',q:'宗教建筑除满足礼拜活动外，还常承担什么作用？',options:['象征信仰并营造神圣空间','只作为商品仓库','取消共同体活动','与文化艺术无关'],answer:0,explain:'宗教建筑通过空间、光线、尺度、装饰和象征形象，组织宗教仪式并营造神圣氛围，凝聚信仰共同体。',keywords:'宗教仪式｜象征信仰｜神圣空间',memorize:'宗教建筑既服务宗教仪式，也通过象征性空间营造神圣氛围、表达信仰。'},
 {id:'a25',type:'choice',chapter:'第五章 宗教建筑',section:'基督教建筑',q:'哥特式教堂常用高耸空间、尖拱和彩色玻璃，主要产生什么效果？',options:['强调向上感和神秘宗教氛围','降低室内高度','完全取消光线','模仿普通住宅'],answer:0,explain:'尖拱、肋架拱顶和飞扶壁支持高耸空间，彩色玻璃让光线具有象征意义，共同形成向上、超越世俗的宗教感受。',keywords:'高耸｜尖拱｜彩色玻璃｜向上感',memorize:'哥特式教堂以高耸空间、尖拱和彩色玻璃营造向上感与神秘宗教氛围。'},
 {id:'a26',type:'choice',chapter:'第五章 宗教建筑',section:'佛教建筑',q:'中国佛塔最初与佛教中的什么功能关系最密切？',options:['纪念和供奉佛教圣物','专门进行商业交易','作为普通住宅','替代城市道路'],answer:0,explain:'佛塔源于印度窣堵坡，最初用于安置和供奉佛舍利，传入中国后与本土楼阁建筑形式结合。',keywords:'佛舍利｜纪念供奉｜本土化',memorize:'佛塔最初用于纪念佛陀、供奉佛舍利，传入中国后逐渐与本土建筑形式结合。'},
 {id:'a27',type:'choice',chapter:'第六章 建筑传承与现代建筑',section:'传统建筑传承',q:'现代建筑传承传统，较合理的方式是什么？',options:['机械复制古代形式','理解传统空间、文化精神和建造智慧并进行当代表达','彻底否定传统','只粘贴装饰符号'],answer:1,explain:'真正的传承不是表面复古，而是理解传统的空间组织、环境关系、材料智慧和文化精神，再回应现代功能与技术。',keywords:'理解传统｜当代表达｜功能技术',memorize:'建筑传承应理解传统的空间与文化精神，并结合现代功能、材料和技术进行当代表达。'},
 {id:'a28',type:'choice',chapter:'第六章 建筑传承与现代建筑',section:'现代建筑思想',q:'现代主义建筑强调“形式追随功能”，主要反对什么？',options:['建筑满足使用需求','脱离结构和功能的表面装饰堆砌','采用新材料和新技术','合理组织空间'],answer:1,explain:'现代主义重视功能、结构、材料和工业技术，反对与实际需求无关的历史样式模仿和繁复装饰。',keywords:'形式追随功能｜结构材料｜反对装饰堆砌',memorize:'现代主义建筑强调功能、结构和新技术，反对脱离实际需求的样式模仿与装饰堆砌。'},
 {id:'a29',type:'choice',chapter:'第六章 建筑传承与现代建筑',section:'建筑与环境',q:'优秀现代建筑处理建筑与环境关系时，应当怎么做？',options:['忽视场地和气候','综合考虑场地、气候、文化与人的使用体验','只追求奇特造型','让所有地区使用同一方案'],answer:1,explain:'建筑不是孤立物体，应回应地形、气候、城市肌理和地域文化，并为使用者创造适宜空间。',keywords:'场地｜气候｜地域文化｜使用体验',memorize:'优秀建筑应综合回应场地、气候、地域文化与人的使用体验。'},
 {id:'f4',type:'fill',chapter:'第三章 民居与地域气候',section:'民居特征',q:'传统民居通过空间与构造适应地域____和生活____。',options:['气候','方式','价格','广告'],answers:[0,1],explain:'地域气候影响通风、采光、保温和防雨，生活方式影响房间关系、院落组织和公共空间。',keywords:'地域气候｜生活方式',memorize:'传统民居通过空间与构造适应地域气候和生活方式。'},
 {id:'f5',type:'fill',chapter:'第四章 园林与宫殿',section:'园林手法',q:'中国传统园林常通过____、对景和曲折空间形成景观层次。',options:['借景','封闭','复制','拆除'],answers:[0],explain:'借景把园外或远处景物纳入观赏画面，使有限园林空间获得更丰富的层次。',keywords:'借景｜对景｜空间层次',memorize:'中国传统园林常通过借景、对景和曲折空间形成丰富的景观层次。'},
 {id:'f6',type:'fill',chapter:'第五章 宗教建筑',section:'宗教空间',q:'宗教建筑通过空间、光线和象征形象营造____氛围。',options:['神圣','商业','日常办公','交通'],answers:[0],explain:'空间尺度、光线方向和宗教符号共同服务仪式，帮助人进入特定的精神体验。',keywords:'空间｜光线｜象征｜神圣氛围',memorize:'宗教建筑通过空间、光线和象征形象营造神圣氛围、表达宗教信仰。'},
 {id:'f7',type:'fill',chapter:'第六章 建筑传承与现代建筑',section:'现代建筑',q:'现代主义建筑强调形式追随____，并重视结构、材料和技术。',options:['功能','装饰','价格','流行'],answers:[0],explain:'形式追随功能强调建筑形态应从使用需求、结构逻辑和材料技术出发。',keywords:'形式追随功能｜结构｜材料｜技术',memorize:'现代主义建筑强调形式追随功能，并重视结构、材料和现代技术。'}
];
questionBank.forEach(q=>{if(!q.answerText)q.answerText=q.memorize||q.options?.[q.answer]||q.answers?.map(i=>q.options[i]).join('、')||''});

const initialState={streak:0,xp:0,completed:0,reviewDone:0,completedIds:[],mistakes:[],mastered:[],view:'home',studyIndex:0,dailyDate:'',dailyTask:[],dailyIndex:0,dailyAnswers:{},dailyDone:false,snapshots:[],syncKey:'',syncEndpoint:'',lastRemoteSync:''};
let state=loadState();
let viewHistory=[];
let syncKeyVisible=false;
const content=document.getElementById('appContent');
const toast=document.getElementById('toast');

function loadState(){
  let saved=null;try{saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||localStorage.getItem('revision-route-state-v2')||'null')}catch(e){}
  const next={...initialState,...(saved||{})};
  if(!Array.isArray(next.mistakes))next.mistakes=[];
  if(!Array.isArray(next.mastered))next.mastered=[];
  if(!Array.isArray(next.completedIds))next.completedIds=[];
  if(!next.dailyAnswers||typeof next.dailyAnswers!=='object')next.dailyAnswers={};
  if(!Array.isArray(next.snapshots))next.snapshots=[];
  return next;
}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));const s=document.querySelector('.sync-label');if(s)s.textContent='已自动保存'}
function notify(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)}
function today(){return new Date().toISOString().slice(0,10)}
function daysLeft(){return Math.max(0,Math.ceil((examDate-new Date())/86400000))}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function getQuestion(id){return questionBank.find(q=>q.id===id)}
function shell(title,eyebrow,body){const back=state.view==='home'?'':`<button class="back-link" onclick="goBack()">← 返回上一页</button>`;return `<div class="content">${back}<div class="eyebrow">${eyebrow}</div><h1 class="page-title">${title}</h1>${body}</div>`}
function ensureDailyTask(){
  const date=today();
  if(!state.dailyTask.length || (state.dailyDone&&state.dailyDate!==date)){
    const choices=questionBank.filter(q=>q.type==='choice');
    const mem=questionBank.filter(q=>q.type==='memorize');
    const ordered=[...choices].sort((a,b)=>(state.mistakes.some(x=>x.id===b.id)?1:0)-(state.mistakes.some(x=>x.id===a.id)?1:0));
    state.dailyTask=[...ordered.slice(0,DAILY_CHOICE_COUNT).map(q=>q.id),...mem.slice(0,DAILY_MEMORIZE_COUNT).map(q=>q.id)];
    state.dailyDate=date;state.dailyIndex=0;state.dailyAnswers={};state.dailyDone=false;save();
  }
}
function currentQuestion(){ensureDailyTask();return getQuestion(state.dailyTask[state.dailyIndex])||questionBank[0]}
function answerFor(id){return state.dailyAnswers[id]||null}
function progressPercent(){return Math.round((Object.keys(state.dailyAnswers).filter(id=>state.dailyAnswers[id]?.answered).length/17)*100)}
function upsertMistake(q,userAnswer){
  let item=state.mistakes.find(x=>x.id===q.id);
  if(item){item.wrongCount=(item.wrongCount||1)+1;item.correctStreak=0;item.userAnswer=userAnswer;item.lastWrongAt=new Date().toISOString();item.nextReviewAt=new Date(Date.now()+86400000).toISOString()}
  else state.mistakes.unshift({id:q.id,question:q.q,chapter:q.chapter,type:q.type,userAnswer,answer:q.answerText||q.memorize||q.options?.[q.answer]||q.answers?.map(i=>q.options[i]).join('、'),explain:q.explain,keywords:q.keywords,wrongCount:1,correctStreak:0,lastWrongAt:new Date().toISOString(),nextReviewAt:new Date(Date.now()+86400000).toISOString()});
}
function markCorrect(q){
  const item=state.mistakes.find(x=>x.id===q.id);
  if(item){item.correctStreak=(item.correctStreak||0)+1;if(item.correctStreak>=2){state.mistakes=state.mistakes.filter(x=>x.id!==q.id);state.mastered.unshift({...item,masteredAt:new Date().toISOString()})}}
}
function submitAnswer(value){
  const q=currentQuestion();if(answerFor(q.id)?.answered)return;
  let correct=false;
  if(q.type==='choice')correct=Number(value)===q.answer;
  if(q.type==='fill')correct=Array.isArray(value)&&value.length===q.answers.length&&value.every((x,i)=>Number(x)===q.answers[i]);
  const result={answered:true,correct,userAnswer:value,submittedAt:new Date().toISOString()};state.dailyAnswers[q.id]=result;
  if(correct){state.xp+=q.type==='memorize'?10:20;markCorrect(q)}else upsertMistake(q,Array.isArray(value)?value.map(i=>q.options[i]).join('、'):q.options?.[value]||'未选择');
  save();render();notify(correct?'回答正确，已保存':'已记录错题，先看解析');
}
function submitMemorize(){const q=currentQuestion();state.dailyAnswers[q.id]={answered:true,correct:true,userAnswer:'已背诵',submittedAt:new Date().toISOString()};state.xp+=10;markCorrect(q);save();render();notify('背诵完成，已保存')}
function retryCurrent(){const q=currentQuestion();delete state.dailyAnswers[q.id];save();render()}
function previousQuestion(){if(state.dailyIndex>0){state.dailyIndex--;save();render()}}
function nextQuestion(){if(state.dailyIndex<state.dailyTask.length-1){state.dailyIndex++;save();render()}else{state.dailyDone=true;save();render();notify('今日17题已完成')}}
function resetDaily(){state.dailyDate=today();state.dailyIndex=0;state.dailyAnswers={};state.dailyDone=false;save();render();notify('今日刷题已重新开始')}
function home(){ensureDailyTask();const done=Object.keys(state.dailyAnswers).filter(id=>state.dailyAnswers[id]?.answered).length;const q=currentQuestion();return shell('今天，向前走 <em>1%</em>。','DAY '+state.dailyDate.replaceAll('-','.'),`<p class="lede">今天完成 ${done}/17 题，系统会自动保存，你可以随时离开，明天继续。</p><div class="hero-grid"><section class="hero-card"><div class="eyebrow" style="color:#a8dfc3">当前章节 · ${q.chapter}</div><h2>${q.section}</h2><p>先完成15道选择题，再完成2道重点背诵题。每道题答完都会显示解析、关键词和背诵答案。</p><div class="progress-label"><span>今日进度</span><span>${done}/17</span></div><div class="progress"><i style="width:${done/17*100}%"></i></div><div class="hero-action"><button class="primary-btn" onclick="showView('practice')">${done?'继续刷题':'开始今日17题'}　→</button></div></section><section class="count-card"><span class="count-label">距离考试</span><div class="days">${daysLeft()} <small>天</small></div><div class="count-detail">首轮学习还剩 <strong>${Math.max(daysLeft()-28,0)} 天</strong><br>然后进入28天循环复习</div></section></div><div class="stats"><div class="stat"><span>今日完成</span><strong>${done}<small> / 17题</small></strong><small>${state.dailyDone?'今日任务已完成':'继续保持节奏'}</small></div><div class="stat"><span>错题待复习</span><strong>${state.mistakes.length}<small> 题</small></strong><small>全部记录在错题库</small></div><div class="stat"><span>累计经验</span><strong>${state.xp}<small> XP</small></strong><small>连续学习 ${state.streak} 天</small></div></div><div class="section-head"><div><h3>今日任务</h3><p>答完一题，先理解，再记忆</p></div><button class="text-btn" onclick="showView('mistakes')">查看错题 →</button></div><div class="task-grid"><article class="task"><div class="task-top"><div class="task-icon coral">A</div><span class="task-tag">选择题 · 15题</span></div><h4>核心概念刷题</h4><p>从艺术本质、功能、创作和鉴赏开始。</p><button onclick="showView('practice')">开始刷题 →</button></article><article class="task"><div class="task-top"><div class="task-icon mint">记</div><span class="task-tag">重点背诵 · 2题</span></div><h4>必须背下来的答案</h4><p>答完后显示可直接背诵版本。</p><button onclick="showView('practice')">进入背诵 →</button></article><article class="task"><div class="task-top"><div class="task-icon yellow">填</div><span class="task-tag">额外练习</span></div><h4>关键词填空</h4><p>用候选关键词完成艺术概论术语。</p><button onclick="showView('fillPractice')">练填空 →</button></article></div>`)}
function practice(){ensureDailyTask();const q=currentQuestion();const idx=state.dailyIndex+1;const result=answerFor(q.id);let body='';if(q.type==='choice')body=`<div class="quiz-options">${q.options.map((o,i)=>`<button class="quiz-option ${result?(result.correct&&i===q.answer?'correct':!result.correct&&i===Number(result.userAnswer)?'wrong':''):''}" ${result?'disabled':''} onclick="submitAnswer(${i})"><span>${String.fromCharCode(65+i)}</span>${o}</button>`).join('')}</div>`;if(q.type==='memorize')body=result?`<div class="answer-box"><span>可直接背诵</span><p>${q.answerText}</p></div>`:`<div class="memorize-start"><p>请先看题目，在心里完整背诵，再点击确认。</p><button class="primary-btn" onclick="submitMemorize()">我已背诵　→</button></div>`;const analysis=result?`<div class="feedback ${result.correct?'good':'bad'}"><strong>${result.correct?'回答正确':'回答错误'}</strong><p>${q.explain}</p><div class="key-box"><span>记忆关键词</span><strong>${q.keywords}</strong></div><div class="answer-box"><span>可直接背诵</span><p>${q.answerText||q.options?.[q.answer]||q.answers.map(i=>q.options[i]).join('、')}</p></div></div>`:'';return shell('今天的17题','DAILY PRACTICE · '+idx+' / 17',`<div class="practice-head"><span>${q.type==='choice'?'选择题':q.type==='memorize'?'重点背诵':'填空题'}</span><span>${q.chapter} · ${q.section}</span></div><div class="panel quiz-panel"><div class="progress-label"><span>今日进度</span><span>${idx}/17</span></div><div class="progress"><i style="width:${idx/17*100}%"></i></div><h2>${q.q}</h2>${body}${analysis}<div class="lesson-actions"><button class="text-btn" onclick="previousQuestion()" ${state.dailyIndex===0?'disabled':''}>← 上一题</button>${result?'<button class="text-btn" onclick="retryCurrent()">再做一次</button>':''}<button class="primary-btn" onclick="nextQuestion()">${idx===17?'完成今日任务':'下一题'}　→</button></div></div>`)}
function fillPractice(){const q=questionBank.find(x=>x.type==='fill');const picked=state.fillPicked||[];const submitted=state.fillSubmitted;return shell('关键词填空','EXTRA PRACTICE · FILL IN',`<div class="panel quiz-panel"><div class="practice-head"><span>${q.chapter}</span><span>${q.section}</span></div><h2>${q.q}</h2><div class="fill-answer">${picked.map((i,n)=>`<span>${n+1}. ${q.options[i]}</span>`).join('')||'请选择关键词填入答案'}</div><div class="keyword-options">${q.options.map((o,i)=>`<button class="keyword-chip ${picked.includes(i)?'selected':''}" onclick="pickFill(${i})">${o}</button>`).join('')}</div>${submitted?`<div class="feedback ${state.fillCorrect?'good':'bad'}"><strong>${state.fillCorrect?'回答正确':'再看一遍解析'}</strong><p>${q.explain}</p><div class="key-box"><span>记忆关键词</span><strong>${q.keywords}</strong></div><div class="answer-box"><span>可直接背诵</span><p>${q.memorize}</p></div></div>`:''}<div class="lesson-actions"><button class="text-btn" onclick="showView('home')">返回今日航线</button>${submitted?'<button class="text-btn" onclick="resetFill()">再做一次</button>':'<button class="primary-btn" onclick="submitFill()">提交答案　→</button>'}</div></div>`)}
function pickFill(i){if(state.fillSubmitted)return;state.fillPicked=state.fillPicked||[];if(state.fillPicked.includes(i))state.fillPicked=state.fillPicked.filter(x=>x!==i);else state.fillPicked.push(i);save();render()}
function submitFill(){const q=questionBank.find(x=>x.type==='fill');const picked=state.fillPicked||[];state.fillSubmitted=true;state.fillCorrect=picked.length===q.answers.length&&picked.every((x,i)=>x===q.answers[i]);if(!state.fillCorrect)upsertMistake(q,picked.map(i=>q.options[i]).join('、'));else markCorrect(q);save();render()}
function resetFill(){state.fillPicked=[];state.fillSubmitted=false;state.fillCorrect=false;save();render()}
function mistakes(){const all=[...state.mistakes,...state.mastered];const rows=all.length?all.map(x=>`<div class="review-card"><div class="review-badge">${state.mastered.some(m=>m.id===x.id)?'✓':'!'}</div><div><h4>${escapeHtml(x.question)}</h4><p>${x.chapter} · 错过 ${x.wrongCount||1} 次</p><p class="count-detail">你的答案：${escapeHtml(x.userAnswer||'未记录')}<br>正确答案：${escapeHtml(x.answer||'见解析')}</p></div><button class="primary-btn" onclick="retryMistake('${x.id}')">再练一次</button></div>`).join(''):'<div class="empty-state"><h3>还没有错题</h3><p>答错的题会自动保存到这里，之后可以反复重做。</p></div>';return shell('错题会变成你的线索','MISTAKE VAULT · '+state.mistakes.length+' 待复习',`<p class="lede">全部错题都会保留，不会因为刷新或更新消失。</p><div class="mistake-summary"><span>待复习 ${state.mistakes.length}</span><span>已掌握 ${state.mastered.length}</span></div><div class="panel" style="margin-top:20px">${rows}</div>`)}
function retryMistake(id){const i=state.dailyTask.indexOf(id);if(i>=0){state.dailyIndex=i;state.view='practice'}else{state.view='practice';state.dailyIndex=0}save();render()}
function courseView(){return shell('课程地图','COURSE MAP · 9 CHAPTERS',`<p class="lede">按章节推进，题目会从知识点逐步变成可以写出的答案。</p><div class="panel" style="margin-top:30px">${questionBank.filter((q,i,a)=>a.findIndex(x=>x.chapter===q.chapter)===i).map((q,i)=>`<div class="chapter-row"><span class="chapter-num">0${i+1}</span><div><h4>${q.chapter}</h4><p>${q.section} · 选择、填空与背诵</p></div><span class="row-status">${i===0?'进行中':'待学习'}</span></div>`).join('')}</div>`)}
function review(){return shell('复习，不是重来','SPACED REVIEW · '+state.mistakes.length+' DUE',`<p class="lede">错题会在下一次复习中再次出现，连续答对后才会移入已掌握。</p><div class="panel" style="margin-top:30px">${state.mistakes.length?state.mistakes.map(x=>`<div class="review-card"><div class="review-badge">↻</div><div><h4>${escapeHtml(x.question)}</h4><p>${x.chapter} · 错过 ${x.wrongCount||1} 次</p></div><button class="primary-btn" onclick="retryMistake('${x.id}')">开始复习</button></div>`).join(''):'<div class="empty-state"><h3>今天没有到期错题</h3><p>继续完成今日17题，新的错题会自动安排复习。</p></div>'}</div>`)}
function settings(){return shell('把数据交给自己保管','SETTINGS · DATA MANAGEMENT',`<p class="lede">自动保存之外，你还可以随时导出、存档和恢复学习进度。</p><div class="panel settings-panel" style="margin-top:30px"><div class="setting-row"><div><strong>导出当前进度</strong><br><span>保存为 JSON 文件，可在更新后恢复</span></div><button class="primary-btn" onclick="exportData()">导出备份</button></div><div class="setting-row"><div><strong>导入进度备份</strong><br><span>从之前导出的文件恢复学习状态</span></div><label class="primary-btn" for="backupInput">选择文件</label><input id="backupInput" type="file" accept=".json" hidden onchange="importData(this)"></div><div class="setting-row"><div><strong>创建版本存档</strong><br><span>为当前进度留下可恢复的时间点</span></div><button class="primary-btn" onclick="createSnapshot()">创建存档</button></div><div class="snapshot-list">${state.snapshots.length?state.snapshots.map((s,i)=>`<div class="snapshot"><div><strong>${s.createdAt}</strong><span>${s.completed}题 · ${s.mistakes}道错题 · ${s.streak}天连续学习</span></div><button class="text-btn" onclick="restoreSnapshot(${i})">恢复</button></div>`).join(''):'<p class="count-detail">还没有版本存档。</p>'}</div><div class="danger-zone"><strong>清除全部学习进度</strong><p>会删除题目记录、错题、经验值和连续学习天数。</p><button class="danger-btn" onclick="clearAllData()">清除并重新开始</button></div></div>`)}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='复习航线-进度备份-'+today()+'.json';a.click();URL.revokeObjectURL(a.href);notify('进度备份已导出')}
function importData(input){const file=input.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const imported=JSON.parse(reader.result);if(!imported||typeof imported!=='object')throw new Error();state={...initialState,...imported};save();render();notify('进度备份已恢复')}catch(e){notify('备份文件无法读取')}};reader.readAsText(file)}
function createSnapshot(){state.snapshots.unshift({createdAt:new Date().toLocaleString('zh-CN'),completed:Object.keys(state.dailyAnswers).filter(id=>state.dailyAnswers[id]?.answered).length,mistakes:state.mistakes.length,streak:state.streak,data:JSON.parse(JSON.stringify({...state,snapshots:[]}))});state.snapshots=state.snapshots.slice(0,10);save();render();notify('已创建版本存档')}
function restoreSnapshot(i){const snap=state.snapshots[i];if(!snap)return;if(!confirm('恢复此版本会覆盖当前学习进度，是否继续？'))return;const keep=state.snapshots;state={...initialState,...snap.data,snapshots:keep};save();render();notify('版本存档已恢复')}
function clearAllData(){if(!confirm('此操作会删除学习进度、错题、经验值和连续学习记录，是否继续？'))return;state={...initialState};save();render();notify('已清除进度，可以重新开始')}
function toggleMemoAnswer(){const q=currentQuestion();state.memoAnswerOpen=state.memoAnswerOpen||{};state.memoAnswerOpen[q.id]=!state.memoAnswerOpen[q.id];save();render()}
function saveMemoDraft(questionId,value){state.memoDrafts=state.memoDrafts||{};state.memoDrafts[questionId]=value;save()}
function completeMemorize(){const q=currentQuestion();if(answerFor(q.id)?.answered)return;const draft=(state.memoDrafts?.[q.id]||'').trim();state.dailyAnswers[q.id]={answered:true,correct:true,userAnswer:draft||'已完成默写',submittedAt:new Date().toISOString()};state.xp+=10;markCorrect(q);save();render();notify('默写已保存')}
function practice(){
  ensureDailyTask();const q=currentQuestion();const idx=state.dailyIndex+1;const result=answerFor(q.id);let body='';let analysis='';
  if(q.type==='choice'){
    body=`<div class="quiz-options">${q.options.map((o,i)=>`<button class="quiz-option ${result?(result.correct&&i===q.answer?'correct':!result.correct&&i===Number(result.userAnswer)?'wrong':''):''}" ${result?'disabled':''} onclick="submitAnswer(${i})"><span>${String.fromCharCode(65+i)}</span>${o}</button>`).join('')}</div>`;
    if(result)analysis=`<div class="feedback ${result.correct?'good':'bad'}"><strong>${result.correct?'回答正确':'回答错误'}</strong><p>${q.explain}</p><div class="key-box"><span>记忆关键词</span><strong>${q.keywords}</strong></div><div class="answer-box"><span>可直接背诵</span><p>${q.answerText}</p></div></div>`;
  }else if(q.type==='memorize'){
    const opened=Boolean(state.memoAnswerOpen?.[q.id]);const draft=escapeHtml(state.memoDrafts?.[q.id]||'');
    body=`<div class="memorize-workspace"><button class="answer-toggle" onclick="toggleMemoAnswer()">${opened?'关闭答案':'查看答案'}</button>${opened?`<div class="answer-box memo-answer"><span>标准背诵答案</span><p>${q.answerText}</p></div>`:''}<label class="memo-label" for="memoDraft">默写区</label><textarea id="memoDraft" class="memo-draft" placeholder="先凭记忆写下答案，再选择查看答案核对。" oninput="saveMemoDraft('${q.id}',this.value)">${draft}</textarea>${result?'<p class="memo-saved">✓ 默写内容已自动保存</p>':'<button class="primary-btn" onclick="completeMemorize()">完成默写　→</button>'}</div>`;
    if(result)analysis=`<div class="feedback good"><strong>默写已保存</strong><p>${q.explain}</p><div class="key-box"><span>记忆关键词</span><strong>${q.keywords}</strong></div></div>`;
  }
  return shell('今天的17题','DAILY PRACTICE · '+idx+' / 17',`<div class="practice-head"><span>${q.type==='choice'?'选择题':'重点背诵'}</span><span>${q.chapter} · ${q.section}</span></div><div class="panel quiz-panel"><div class="progress-label"><span>今日进度</span><span>${idx}/17</span></div><div class="progress"><i style="width:${idx/17*100}%"></i></div><h2>${q.q}</h2>${body}${analysis}<div class="lesson-actions"><button class="text-btn" onclick="previousQuestion()" ${state.dailyIndex===0?'disabled':''}>← 上一题</button>${result?'<button class="text-btn" onclick="retryCurrent()">再做一次</button>':''}<button class="primary-btn" onclick="nextQuestion()">${idx===17?'完成今日任务':'下一题'}　→</button></div></div>`)
}
function courseView(){const rows=syllabusChapters.map((c,i)=>{const covered=questionBank.filter(q=>questionChapter[q.id]===c.id).length;return `<div class="chapter-row"><span class="chapter-num">${String(i+1).padStart(2,'0')}</span><div><h4>${c.title}</h4><p>${c.summary} · 首轮计划 ${c.days} 天 · 当前题库 ${covered} 题</p></div><span class="row-status">${i===0?'进行中':covered?'待学习':'待补题'}</span></div>`}).join('');return shell('课程地图','COURSE MAP · 9 CHAPTERS · 60 DAYS',`<p class="lede">每天17题是当天的练习量，不是一章的总题量。首轮学习按9章分配60天，之后用28天循环复习。</p><div class="panel" style="margin-top:30px">${rows}</div>`)}
function render(){ensureDailyTask();const views={home,practice,fillPractice,course:courseView,review,mistakes,settings};content.innerHTML=(views[state.view]||home)();document.querySelectorAll('.nav-item,.mobile-nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));const streak=document.getElementById('streakSide');if(streak)streak.textContent=state.streak+' 天';const back=document.getElementById('mobileBack');if(back)back.classList.toggle('is-hidden',state.view==='home')}
function showView(view){if(view!==state.view)viewHistory.push(state.view);state.view=view;save();render();window.scrollTo({top:0,behavior:'smooth'})}
function goBack(){state.view=viewHistory.pop()||'home';save();render();window.scrollTo({top:0,behavior:'smooth'})}
document.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)showView(b.dataset.view)});
const requestedView=new URLSearchParams(location.search).get('view');
if(['home','practice','fillPractice','course','review','mistakes','settings'].includes(requestedView))state.view=requestedView;
ensureDailyTask();save();render();

// Cross-device progress sync is enabled after the Cloudflare Worker is deployed.
const SYNC_API_URL='https://yishugailun-sync.yishugailun.workers.dev';
let syncTimer=null;
function syncUrl(){return state.syncEndpoint||SYNC_API_URL}
function scheduleRemoteSave(){if(syncTimer)clearTimeout(syncTimer);if(!syncUrl()||!state.syncKey)return;syncTimer=setTimeout(pushRemoteState,900)}
async function pushRemoteState(showNotice=false){if(!state.syncKey){notify('请先设置同步码');return}try{const res=await fetch(`${syncUrl()}/state/${encodeURIComponent(state.syncKey)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(state)});if(!res.ok)throw new Error('sync failed');state.lastRemoteSync=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(state));const s=document.querySelector('.sync-label');if(s)s.textContent='已同步到云端';if(showNotice){render();notify('本机进度已上传到云端')}}catch(e){const s=document.querySelector('.sync-label');if(s)s.textContent='本地已保存，等待同步';if(showNotice)notify('上传失败，请检查网络后重试')}}
async function pullRemoteState(){if(!syncUrl()||!state.syncKey){notify('请先设置同步码');return}try{const res=await fetch(`${syncUrl()}/state/${encodeURIComponent(state.syncKey)}`);if(res.status===404){notify('云端暂无记录，将当前进度上传');await pushRemoteState();return}if(!res.ok)throw new Error('sync failed');const remote=await res.json();if(!remote||typeof remote!=='object')throw new Error('bad state');if(!confirm('从云端恢复会覆盖本设备当前进度，是否继续？'))return;state={...initialState,...remote,syncKey:state.syncKey,syncEndpoint:state.syncEndpoint,lastRemoteSync:new Date().toISOString()};save();render();notify('已从云端恢复最新进度')}catch(e){notify('云端同步失败，请检查网络或同步码')}}
function newSyncKey(){return(globalThis.crypto?.randomUUID?crypto.randomUUID().replaceAll('-','').slice(0,12):Math.random().toString(36).slice(2,14)).toUpperCase()}
function generateSyncKey(){const input=document.getElementById('syncKeyInput');if(input){input.value=newSyncKey();input.focus();notify('已生成同步码，请点击保存')}}
function saveSyncKeyFromInput(){const input=document.getElementById('syncKeyInput');const clean=(input?.value||'').trim();if(clean.length<8){notify('同步码至少需要8位');return}state.syncKey=clean;state.syncEndpoint=SYNC_API_URL;syncKeyVisible=true;originalSave();render();notify('同步码已保存。新设备请先读取云端进度')}
function toggleSyncKey(){if(!state.syncKey){notify('请先输入并保存同步码');return}syncKeyVisible=!syncKeyVisible;render()}
async function copySyncKey(){if(!state.syncKey){notify('请先设置同步码');return}try{await navigator.clipboard.writeText(state.syncKey);notify('同步码已复制')}catch(e){prompt('请复制下面的同步码',state.syncKey)}}
function maskedSyncKey(){if(!state.syncKey)return'尚未设置';if(syncKeyVisible)return escapeHtml(state.syncKey);return'•'.repeat(Math.max(8,state.syncKey.length-4))+escapeHtml(state.syncKey.slice(-4))}
function formatSyncTime(){if(!state.lastRemoteSync)return'尚未进行云端同步';return'上次同步：'+new Date(state.lastRemoteSync).toLocaleString('zh-CN')}
const originalSave=save;
save=function(){originalSave();scheduleRemoteSave()}
function settings(){return shell('数据与同步','SETTINGS · BACKUP & SYNC',`<p class="lede">学习进度始终先保存在本机；设置同步码后，电脑和手机可以读取同一份云端进度。</p><div class="panel settings-panel" style="margin-top:30px"><section class="sync-card"><strong>跨设备云同步</strong><p class="sync-help">同一个人使用电脑和手机时，两台设备必须填写完全相同的同步码。同步码相当于进度钥匙，请自己保存。</p><div class="sync-code"><code>${maskedSyncKey()}</code>${state.syncKey?`<button class="text-btn" onclick="toggleSyncKey()">${syncKeyVisible?'隐藏':'查看'}</button><button class="text-btn" onclick="copySyncKey()">复制</button>`:''}</div><label class="sync-input-label" for="syncKeyInput">${state.syncKey?'输入新同步码可修改':'输入同步码'}</label><input id="syncKeyInput" class="sync-input" type="text" autocomplete="off" spellcheck="false" placeholder="至少8位，例如 ART00504ABC"><div class="sync-actions"><button class="primary-btn" onclick="saveSyncKeyFromInput()">保存同步码</button><button class="text-btn" onclick="generateSyncKey()">生成新同步码</button><button class="primary-btn" onclick="pullRemoteState()" ${state.syncKey?'':'disabled'}>读取云端进度</button><button class="text-btn" onclick="pushRemoteState(true)" ${state.syncKey?'':'disabled'}>上传本机进度</button></div><p class="sync-help">${escapeHtml(formatSyncTime())}<br>第一次在新手机上使用：先输入电脑的同步码并保存，再点“读取云端进度”。</p></section><div class="setting-row"><div><strong>导出当前进度</strong><br><span>保存 JSON 文件，更新后可恢复。</span></div><button class="primary-btn" onclick="exportData()">导出备份</button></div><div class="setting-row"><div><strong>导入进度备份</strong><br><span>从以前导出的 JSON 文件恢复。</span></div><label class="primary-btn" for="backupInput">选择文件</label><input id="backupInput" type="file" accept=".json" hidden onchange="importData(this)"></div><div class="setting-row"><div><strong>创建版本存档</strong><br><span>在更新前保存一个可恢复的时间点。</span></div><button class="primary-btn" onclick="createSnapshot()">创建存档</button></div><div class="snapshot-list">${state.snapshots.length?state.snapshots.map((s,i)=>`<div class="snapshot"><div><strong>${escapeHtml(s.createdAt)}</strong><span>${s.completed}题 · ${s.mistakes}道错题 · ${s.streak}天连续学习</span></div><button class="text-btn" onclick="restoreSnapshot(${i})">恢复</button></div>`).join(''):'<p class="count-detail">还没有版本存档。</p>'}</div><div class="danger-zone"><strong>清除全部学习进度</strong><p>会删除题目记录、错题、经验值和连续学习天数。</p><button class="danger-btn" onclick="clearAllData()">清除并重新开始</button></div></div>`)}
