/* 艺术博物馆RPG第四版：动作战斗、灵魂答题、装备路线与五地图。 */
const RPG_VIEW_W=960,RPG_VIEW_H=540,RPG_WORLD_W=7600,RPG_GROUND_Y=510;
let rpgInstance=null,rpgScene=null,rpgTestBackup=null,rpgInput={left:false,right:false,jump:false,attack:false,dodge:false};
function isRpgTest(){const q=new URLSearchParams(location.search);return q.has('game-test')||q.has('rpg-test')}
function rpgPersist(){if(!isRpgTest())save()}
function rpgNode(id){return ensureRpgState().route.nodes.find(x=>x.id===Number(id))||ensureRpgState().route.nodes[0]}
function rpgCurrentNode(){const r=ensureRpgState();return rpgNode(r.route.current||r.route.unlocked)}
function rpgMap(node=rpgCurrentNode()){return RPG_MAPS.find(x=>x.id===node.mapId)||RPG_MAPS[0]}
function rpgQuestionsForNode(node,replay=false){
  let original=(node.questionSnapshot||[]).slice(0,10);if(!original.length&&isRpgTest()){const lesson=ensureDailyTask();original=(lesson.items||[]).slice(0,10).map(x=>({id:x.id,q:x.q,answerText:x.answerText,chapter:x.chapter,section:x.section,orderPolicy:answerOrderPolicy(x)}))}if(!replay)return original;
  const due=(state.mistakes||[]).filter(m=>!m.nextReviewAt||new Date(m.nextReviewAt)<=new Date()).slice(0,4).map(m=>{const source=typeof getQuestion==='function'?getQuestion(m.id):null;return source?{id:source.id,q:source.q,answerText:source.answerText||source.memorize||'',chapter:source.chapter,section:source.section,orderPolicy:answerOrderPolicy(source)}:null}).filter(Boolean);
  const seen=new Set(due.map(x=>x.id));return[...due,...original.filter(x=>!seen.has(x.id))].slice(0,10);
}
function rpgEnemyPlan(node,replay=false){
  const questions=rpgQuestionsForNode(node,replay),specs=[
    ['e1','agile',520],['e2','ranged',820],['e3','guardian',1120],['e4','agile',1430],['e5','healer',1760],['e6','berserker',2100],['e7','ranged',2430],['e8','large',2780],['e9','agile',3110],['e10','guardian',3450],['e11','healer',3770],['e12','berserker',4110],['e13','large',4470],['e14','ranged',4800],['e15','guardian',5190],['boss','boss',5850]
  ];
  const soulIds=rpgShuffle(specs.slice(0,-1).map(x=>x[0]),`souls-${node.layoutSeed}-${Date.now()>>16}`).slice(0,Math.min(9,questions.length-1)),assign=[...soulIds,'boss'];
  const scale=rpgLevelScale(node.difficulty);return specs.map(([id,kind,x],i)=>{const def=RPG_MONSTERS[kind],hasSoul=assign.includes(id),questionIndex=assign.indexOf(id),maxHp=Math.round(def.hp*scale.hp);return{id,kind,tier:def.tier,x,y:kind==='ranged'&&i%2?300:435,maxHp,hp:maxHp,attack:Math.round(def.attack*scale.attack),defense:def.defense,skill:def.skill,hasSoul,questionId:questionIndex>=0?questions[questionIndex]?.id:'',alive:true,soulResolved:false,phase:1,healEnergy:0,killSerial:0}})}
function rpgFreshRun(node,replay=false){return{version:RPG_VERSION,nodeId:node.id,mapId:node.mapId,seed:rpgHash(`${node.layoutSeed}-${Date.now()}-${Math.random()}`),replay,status:'ready',startedAt:null,playerX:120,playerY:420,checkpoint:{id:'cp0',x:120,hp:ensureRpgState().player.hp||rpgComputedStats().maxHp,enemySnapshot:[]},checkpoints:['cp0'],enemies:rpgEnemyPlan(node,replay),openedBlocks:[],openedRooms:[],collected:[],earnedCoins:0,earnedXp:0,loot:[],soulsAnswered:[],wrongSouls:[],attempts:{},stars:0}}
function rpgEnsureRun(node,replay=false){const r=ensureRpgState();if(!r.run||r.run.nodeId!==node.id||['completed','failed'].includes(r.run.status))r.run=rpgFreshRun(node,replay);return r.run}
function rpgGameUnlocked(){if(isRpgTest())return true;const r=ensureRpgState(),node=rpgNode(r.route.unlocked),lesson=ensureDailyTask();return Boolean(lesson.done&&node.sourceDate===rpgToday())}
function gameStatusCard(){const r=ensureRpgState(),node=rpgUnlockToday(),map=rpgMap(node),stats=rpgComputedStats(),unlocked=rpgGameUnlocked();return`<section class="game-home-card rpg-home-card ${unlocked?'is-unlocked':'is-locked'}"><div class="rpg-home-poster map-${map.id}"><span>${String(node.id).padStart(2,'0')}</span></div><div><span class="game-kicker">${unlocked?'今日节点已解锁':'完成三轮后解锁'}</span><h3>冒险第${node.id}关 · ${escapeHtml(map.name)}</h3><p>实体战斗削减怪物血量，灵魂离体后用知识击败它。旧关可以反复刷装备和错题。</p><div class="game-home-stats"><span>战力 ${stats.power}</span><span>推荐 ${node.recommendedPower}</span><span>等级 ${r.player.level}</span><span>金币 ${r.player.coins}</span></div><button class="primary-btn" onclick="rpgStartNode(${node.id})" ${unlocked?'':'disabled'}>进入今日新关 →</button><button class="text-btn" onclick="showView('rpgRoute')">查看冒险路线</button></div></section>`}

function rpgCourseView(){const r=ensureRpgState(),chapterRows=syllabusChapters.map((c,i)=>`<div class="chapter-row"><span class="chapter-num">${String(i+1).padStart(2,'0')}</span><div><h4>${c.title}</h4><p>${c.summary} · 首轮计划 ${c.days} 天</p></div><span class="row-status">${i===0?'进行中':'待学习'}</span></div>`).join('');return shell('课程与冒险','COURSE + ADVENTURE',`<div class="course-tabs"><button class="active" onclick="showView('course')">学习章节</button><button onclick="showView('rpgRoute')">冒险路线</button><button onclick="showView('rpgInventory')">装备工坊</button></div><p class="lede">学习章节决定每天10题；冒险路线保存每一关的地图、难度和战利品。</p><div class="panel" style="margin-top:24px">${chapterRows}</div>`)}
function rpgRouteView(){const r=ensureRpgState();rpgEnsureNodes(r.route.unlocked);const stats=rpgComputedStats(),nodes=r.route.nodes.slice(0,Math.min(88,r.route.unlocked+5));return shell('冒险路线','MUSEUM EXPEDITION · 88 NODES',`<div class="course-tabs"><button onclick="showView('course')">学习章节</button><button class="active">冒险路线</button><button onclick="showView('rpgInventory')">装备工坊</button></div><div class="route-summary"><div><span>角色等级</span><strong>${r.player.level}</strong></div><div><span>当前战力</span><strong>${stats.power}</strong></div><div><span>金币</span><strong>${r.player.coins}</strong></div><div><span>艺术粉尘</span><strong>${r.player.dust}</strong></div></div><div class="rpg-route">${nodes.map((n,i)=>{const map=rpgMap(n),locked=n.id>r.route.unlocked,done=n.firstClear||n.status==='completed';return`<article class="route-node ${locked?'locked':done?'done':'current'} map-${map.id}" style="--node-accent:${map.accent};--route-shift:${i%2?1:-1}"><button ${locked?'disabled':''} onclick="rpgStartNode(${n.id},${done})"><span class="node-medal">${locked?'◆':n.id}</span><div><small>${done?'可重复挑战':n.id===r.route.unlocked?'今日新关':'未解锁'}</small><h3>${escapeHtml(map.name)}</h3><p>推荐战力 ${n.recommendedPower} · ${escapeHtml(n.lootPreview)}</p><b>${done?`${'★'.repeat(n.stars)}${'☆'.repeat(3-n.stars)}`:'进入关卡'}</b></div></button></article>`}).join('')}</div>`)}
function rpgRarity(item){return RPG_RARITIES[item?.rarityRank||0]||RPG_RARITIES[0]}
function rpgItemCard(item,index){const rarity=rpgRarity(item),r=ensureRpgState(),equipped=Object.values(r.equipment).flat().includes(item.id),current=item.slot==='weapon'?rpgItemById(r.equipment.weapons[r.equipment.activeWeapon]):rpgItemById(r.equipment[item.slot]),delta=Math.round((item.mainStat-(current?.mainStat||0))*10)/10;return`<article class="gear-card ${equipped?'equipped':''}" style="--rarity:${rarity.color}"><header><span>${rarity.name}</span><b>${escapeHtml(item.name)}${item.upgrade?` ＋${item.upgrade}`:''}${item.locked?' · 已锁定':''}</b></header><p>${item.slot==='weapon'?RPG_WEAPONS[item.baseId]?.name:RPG_ARMOR[item.slot]} · Lv.${item.itemLevel} · 主属性 ${item.mainStat}</p>${!equipped?`<p class="gear-compare">相比当前 ${delta>=0?'+':''}${delta}</p>`:''}<ul>${(item.affixes||[]).map(a=>`<li class="${a.positive?'positive':'negative'}">${a.label} ${a.value>0?'+':''}${a.value}%</li>`).join('')}${item.setId?`<li class="set-bonus">${escapeHtml(rpgMap({mapId:item.setId}).name)}套装</li>`:''}${item.legendaryEffect?`<li class="legendary">${escapeHtml(item.legendaryEffect)}</li>`:''}<li class="negative">代价：${escapeHtml(item.drawback||'无')}</li></ul><footer>${item.slot==='weapon'?`<button onclick="rpgEquipAndRender('${item.id}',${index%3})">装备到${index%3+1}</button>`:`<button onclick="rpgEquipAndRender('${item.id}')">装备</button>`}<button onclick="rpgUpgradeAndRender('${item.id}')">强化</button><button onclick="rpgLockAndRender('${item.id}')">${item.locked?'解锁':'锁定'}</button><button onclick="rpgDismantleAndRender('${item.id}')" ${item.locked||equipped?'disabled':''}>分解</button></footer></article>`}
function rpgInventoryView(){const r=ensureRpgState(),stats=rpgComputedStats(),items=[...r.inventory].sort((a,b)=>b.rarityRank-a.rarityRank||b.itemLevel-a.itemLevel);return shell('装备工坊','GEAR WORKSHOP · 120 SLOTS',`<div class="course-tabs"><button onclick="showView('course')">学习章节</button><button onclick="showView('rpgRoute')">冒险路线</button><button class="active">装备工坊</button></div><div class="workshop-hero"><div><span>战力</span><strong>${stats.power}</strong><p>生命 ${stats.maxHp} · 攻击 ${stats.attack} · 防御 ${stats.defense} · 暴击 ${Math.round(stats.crit*100)}%</p></div><div class="currency"><b>金币 ${r.player.coins}</b><b>粉尘 ${r.player.dust}</b><b>背包 ${r.inventory.length}/120</b></div></div><section class="loadout"><h3>当前携带</h3><div>${r.equipment.weapons.map((id,i)=>{const item=rpgItemById(id);return`<button class="weapon-slot ${i===r.equipment.activeWeapon?'active':''}" onclick="rpgActivateWeapon(${i})"><span>${i+1}</span><b>${item?escapeHtml(item.name):'空武器栏'}</b></button>`}).join('')}</div></section><div class="gear-grid">${items.map(rpgItemCard).join('')}</div>`)}
function rpgEquipAndRender(id,index=0){rpgEquipItem(id,index);save();render();notify('装备已更新')}
function rpgUpgradeAndRender(id){const result=rpgUpgradeItem(id);save();render();notify(result.message)}
function rpgDismantleAndRender(id){const result=rpgDismantleItem(id);save();render();notify(result.message)}
function rpgLockAndRender(id){const locked=rpgToggleItemLock(id);save();render();notify(locked?'装备已锁定':'装备已解锁')}
function rpgActivateWeapon(index){ensureRpgState().equipment.activeWeapon=index;save();render();notify(`已切换到武器栏${index+1}`)}

function rpgStartNode(id,replay=false){const r=ensureRpgState(),node=rpgNode(id);if(node.id>r.route.unlocked){notify('先完成前一关');return}if(!node.firstClear&&node.id===r.route.unlocked&&!rpgGameUnlocked()){notify('先完成今天10题的三轮练习');return}r.route.current=node.id;rpgEnsureRun(node,Boolean(replay||node.firstClear));state.view='rpgGame';rpgPersist();render()}
function enterDailyGame(){const node=rpgUnlockToday();rpgStartNode(node.id,false)}
function rpgExitGame(){rpgDestroy();document.body.classList.remove('rpg-mode');if(isRpgTest()&&rpgTestBackup){state.rpg=JSON.parse(rpgTestBackup);rpgTestBackup=null}state.view='home';rpgPersist();render()}
function rpgGameView(){const r=ensureRpgState(),node=rpgCurrentNode(),run=rpgEnsureRun(node,node.firstClear),map=rpgMap(node),stats=rpgComputedStats(),test=isRpgTest();return`<div class="rpg-shell map-${map.id}"><div id="rpgCanvas"></div><div class="rpg-hud"><span class="test-badge">${test?'独立测试 · 不保存':''}</span><div class="hud-health"><i id="rpgPlayerHp" style="width:${Math.max(0,r.player.hp/stats.maxHp*100)}%"></i><b id="rpgHpLabel">${Math.ceil(r.player.hp)}/${stats.maxHp}</b></div><span>Lv.${r.player.level}</span><span>金币 <b id="rpgCoins">${r.player.coins}</b></span><span>灵魂 <b id="rpgSoulCount">${run.soulsAnswered.length}/10</b></span><span>武器 <b id="rpgWeaponName">${escapeHtml(stats.weaponItem.name)}</b></span><span>护盾 <b id="rpgShield">${r.player.shield?'有':'无'}</b></span><button onclick="rpgExitGame()">撤离</button></div><div class="weapon-switch">${r.equipment.weapons.map((id,i)=>`<button data-weapon="${i}" onclick="rpgSwitchWeapon(${i})" class="${i===r.equipment.activeWeapon?'active':''}"><span>${i+1}</span>${escapeHtml(rpgItemById(id)?.name||'空')}</button>`).join('')}</div><div class="quick-items">${r.equipment.quickItems.map((id,i)=>`<button onclick="rpgUseItem(${i})"><span>${i+4}</span>${RPG_CONSUMABLES[id]?.icon||'?'}<b>${r.consumables[id]||0}</b></button>`).join('')}</div><div class="rpg-controls"><div><button data-rpg="left">←</button><button data-rpg="right">→</button></div><div><button data-rpg="jump">跳</button><button data-rpg="dodge">闪</button><button data-rpg="attack">攻</button></div></div><div class="rotate-note"><div><strong>请把手机横过来</strong><p>横屏后才能完整操作武器、躲避和道具。</p></div></div><div class="rpg-start" id="rpgStart"><div><small>第${node.id}关 · 推荐战力 ${node.recommendedPower}</small><h2>${escapeHtml(map.name)}</h2><p>${escapeHtml(map.hazard)} · ${escapeHtml(map.boss)}。本关有10只灵魂怪，击碎实体血条后才会出现题目。</p><button onclick="rpgLaunch()">开始探索</button></div></div><div id="rpgModal"></div></div>`}
function rpgSwitchWeapon(index){const r=ensureRpgState();if(!r.equipment.weapons[index]){notify('这个武器栏是空的');return}r.equipment.activeWeapon=index;const stats=rpgComputedStats();r.player.hp=Math.min(r.player.hp,stats.maxHp);rpgScene?.refreshWeapon();rpgRenderHud();rpgPersist()}
function rpgUseItem(index){const r=ensureRpgState(),id=r.equipment.quickItems[index];if(!id||!r.consumables[id]){notify('道具数量不足');return}const stats=rpgComputedStats();r.consumables[id]--;if(id==='potion')r.player.hp=Math.min(stats.maxHp,r.player.hp+stats.maxHp*.35);if(id==='mana')r.player.mana=Math.min(stats.maxMana,r.player.mana+stats.maxMana*.45);if(id==='shield'){if(r.player.shield){r.consumables.hint++;notify('已有护盾，转化为1张提示卡')}else r.player.shield=true}if(id==='speed')rpgScene?.applyBuff('speed',12000);if(id==='polish')rpgScene?.applyBuff('polish',12000);if(id==='lens')rpgScene?.applyBuff('lens',20000);if(id==='silence')rpgScene?.silenceHealers();if(id==='hint'&&rpgScene?.soulBattle)rpgUseSoulHint();rpgScene?.syncShieldEffect();rpgRenderHud();rpgPersist()}
function rpgRenderHud(){const r=ensureRpgState(),stats=rpgComputedStats(),run=r.run,hp=document.getElementById('rpgPlayerHp'),label=document.getElementById('rpgHpLabel');r.player.hp=Math.min(r.player.hp,stats.maxHp);if(hp)hp.style.width=`${Math.max(0,r.player.hp/stats.maxHp*100)}%`;if(label)label.textContent=`${Math.ceil(r.player.hp)}/${stats.maxHp}`;const coins=document.getElementById('rpgCoins'),soul=document.getElementById('rpgSoulCount'),weapon=document.getElementById('rpgWeaponName'),shield=document.getElementById('rpgShield');if(coins)coins.textContent=r.player.coins;if(soul)soul.textContent=`${run?.soulsAnswered?.length||0}/10`;if(weapon)weapon.textContent=stats.weaponItem.name;if(shield)shield.textContent=r.player.shield?'有':'无';document.querySelectorAll('[data-weapon]').forEach((b,i)=>b.classList.toggle('active',i===r.equipment.activeWeapon))}
function rpgLaunch(){if(isRpgTest()&&!rpgTestBackup)rpgTestBackup=JSON.stringify(state.rpg);document.getElementById('rpgStart')?.remove();rpgDestroy();const config={type:Phaser.AUTO,parent:'rpgCanvas',width:RPG_VIEW_W,height:RPG_VIEW_H,backgroundColor:'#091522',pixelArt:true,physics:{default:'arcade',arcade:{gravity:{y:920},debug:false}},scene:[RpgScene]};rpgInstance=new Phaser.Game(config)}
function rpgDestroy(){if(rpgInstance){rpgInstance.destroy(true);rpgInstance=null;rpgScene=null}}
function rpgBeep(freq=440,duration=.07){try{const ctx=rpgBeep.ctx||(rpgBeep.ctx=new AudioContext()),o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=freq;o.type='square';g.gain.setValueAtTime(.025,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+duration);o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+duration)}catch(e){}}
function rpgDamageValue(attack,multiplier,defense,critChance=0){const crit=Math.random()<critChance?1.75:1;return{amount:Math.max(1,Math.round(attack*multiplier*crit*100/(100+defense))),crit:crit>1}}

class RpgScene extends Phaser.Scene{
  constructor(){super('rpg')}
  preload(){this.load.spritesheet('rpg-hero','assets/art/hero-sprites-v2.png',{frameWidth:256,frameHeight:256});this.load.spritesheet('rpg-enemy','assets/art/enemy-sprites-v2.png',{frameWidth:256,frameHeight:256});this.load.spritesheet('rpg-boss','assets/art/boss-sprites-v2.png',{frameWidth:256,frameHeight:256});this.load.spritesheet('rpg-soul','assets/art/enemy-souls-v4.png',{frameWidth:256,frameHeight:256});this.load.image('rpg-backgrounds','assets/art/chapter-backgrounds-v2.png')}
  create(){
    rpgScene=this;const r=ensureRpgState(),run=r.run,node=rpgCurrentNode();run.status='playing';run.startedAt=run.startedAt||new Date().toISOString();this.node=node;this.run=run;this.stats=rpgComputedStats();this.lastAttack=-Infinity;this.lastDamage=0;this.lastDodge=-Infinity;this.invulnerableUntil=0;this.jumpCount=0;this.combo=0;this.comboAt=0;this.buffs={};this.soulBattle=null;this.physics.world.setBounds(0,0,RPG_WORLD_W,RPG_VIEW_H);this.cameras.main.setBounds(0,0,RPG_WORLD_W,RPG_VIEW_H).setBackgroundColor('#07131f');this.makeBackground();this.solids=this.physics.add.staticGroup();this.platforms=this.physics.add.staticGroup();this.makeSolid(0,RPG_GROUND_Y,RPG_WORLD_W,60);this.makeLayout();
    this.player=this.physics.add.sprite(run.playerX||120,run.playerY||420,'rpg-hero',0).setScale(.42).setDepth(20);this.player.body.setSize(74,128).setOffset(91,126).setCollideWorldBounds(true);this.player.setDragX(1250).setMaxVelocity(this.stats.moveSpeed,680);for(const s of this.solids.getChildren())this.physics.add.collider(this.player,s);for(const p of this.platforms.getChildren())this.physics.add.collider(this.player,p,null,this.canLand,this);this.cameras.main.startFollow(this.player,true,.11,.11).setDeadzone(200,100);
    this.createHeroAnimations();this.player.play('rpg-idle');this.keys=this.input.keyboard.addKeys('A,D,F,J,K,SPACE,ONE,TWO,THREE,FOUR,FIVE,SIX');this.cursors=this.input.keyboard.createCursorKeys();this.weaponFx=this.add.container(this.player.x,this.player.y).setDepth(22);this.refreshWeapon();this.syncShieldEffect();
    this.enemyGroup=this.physics.add.group();this.enemies=[];for(const saved of run.enemies.filter(x=>x.alive))this.spawnEnemy(saved);
    this.projectiles=this.physics.add.group({allowGravity:false});this.enemyShots=this.physics.add.group({allowGravity:false});this.physics.add.overlap(this.player,this.enemyShots,(p,s)=>{s.destroy();this.damagePlayer(s.damage||7,s.x)});this.physics.add.collider(this.projectiles,this.solids,p=>p.destroy());this.physics.add.collider(this.enemyShots,this.solids,p=>p.destroy());this.createBlocks();this.createCheckpoints();this.createRooms();this.bindControls();rpgRenderHud();rpgPersist();
  }
  createHeroAnimations(){const add=(key,frames,rate=8,repeat=-1)=>{if(!this.anims.exists(key))this.anims.create({key,frames:frames.map(frame=>({key:'rpg-hero',frame})),frameRate:rate,repeat})};add('rpg-idle',[0,1,2,3,4,5],5);add('rpg-run',[6,7,8,9,10,11],11);add('rpg-attack',[15,16,17],14,0);}
  makeBackground(){const map=rpgMap(this.node),panel=map.panel,key=`rpg-map-${panel}`;if(!this.textures.exists(key)){const source=this.textures.get('rpg-backgrounds').getSourceImage(),w=512,h=panel>=6?342:341,x=panel%3*512,y=Math.floor(panel/3)*341,tex=this.textures.createCanvas(key,w,h);tex.context.drawImage(source,x,y,w,h,0,0,w,h);tex.refresh()}for(let x=0;x<RPG_WORLD_W;x+=960)this.add.image(x+480,270,key).setDisplaySize(960,540).setDepth(-30);this.add.rectangle(RPG_WORLD_W/2,270,RPG_WORLD_W,540,0x06111d,.22).setDepth(-29);for(let i=0;i<60;i++){const mote=this.add.circle((i*173)%RPG_WORLD_W,80+(i*73)%350,1+i%3,0xf3d58a,.18).setDepth(-25);this.tweens.add({targets:mote,y:mote.y-35,alpha:{from:.05,to:.45},duration:1900+i%7*220,yoyo:true,repeat:-1})}}
  makeSolid(x,y,w,h=24){const o=this.add.rectangle(x+w/2,y,w,h,0x765332).setStrokeStyle(3,0xd8b66b).setDepth(3);this.physics.add.existing(o,true);this.solids.add(o);return o}
  makePlatform(x,y,w,h=20){const o=this.add.rectangle(x+w/2,y,w,h,0x9a7040).setStrokeStyle(3,0xf0ca78).setDepth(5);this.physics.add.existing(o,true);o.body.checkCollision.down=false;o.body.checkCollision.left=false;o.body.checkCollision.right=false;this.platforms.add(o);return o}
  canLand(player,p){return player.body.velocity.y>=-5&&player.body.bottom<=p.body.top+18}
  canEnemyLand(e,p){return e.body.velocity.y>=-5&&e.body.bottom<=p.body.top+18}
  makeLayout(){const rand=rpgRandom(this.node.layoutSeed),patterns=[[420,350,230],[760,270,190],[1100,380,250],[1450,295,220],[1800,390,260],[2160,290,230],[2510,370,240],[2860,265,200],[3200,385,270],[3590,280,220],[3950,370,260],[4320,270,210],[4690,385,260],[5070,280,220],[5450,370,250]];patterns.forEach((p,i)=>this.makePlatform(p[0]+Math.round(rand()*45),p[1]+Math.round((rand()-.5)*30),p[2]));for(const x of [1500,3000,4550])this.makeSolid(x,435,70,75);const map=this.node.mapId;if(map==='gallery'){for(const x of [900,2300,4100,5300])this.add.rectangle(x,175,150,110,0x3a1e1c,.35).setStrokeStyle(8,0xc69344).setDepth(-10)}if(map==='blueprint'){for(const x of [700,1850,3400,5000]){const grid=this.add.grid(x,210,260,210,26,21,0x103f59,.25,0x6ec8ef,.28).setDepth(-10);this.tweens.add({targets:grid,alpha:{from:.25,to:.6},duration:1100,yoyo:true,repeat:-1})}}if(map==='garden'){for(const x of [650,1700,2950,4350,5500]){this.add.circle(x,430,80,0x184a35,.35).setDepth(-8);for(let i=0;i<5;i++)this.add.circle(x-50+i*24,390-(i%2)*16,13,0x78c68d,.4).setDepth(-7)}}if(map==='cathedral'){for(const x of [1200,2700,4300,5400]){const bell=this.add.triangle(x,130,0,70,35,0,70,70,0xd8ae53,.35).setDepth(-9);this.tweens.add({targets:bell,angle:{from:-10,to:10},duration:1250,yoyo:true,repeat:-1})}}if(map==='modern'){for(const x of [850,2000,3300,4700,5600]){const art=this.add.star(x,220,6,30,85,0x57d6e6,.18).setStrokeStyle(3,0xef6ec8,.35).setDepth(-8);this.tweens.add({targets:art,angle:360,duration:7000,repeat:-1})}}}
  spawnEnemy(saved){const row=saved.kind==='ranged'?1:saved.kind==='large'?2:saved.kind==='healer'?3:saved.kind==='boss'?1:0,texture=saved.kind==='boss'?'rpg-boss':'rpg-enemy',scale=saved.tier==='small'?.31:saved.tier==='medium'||saved.tier==='healer'?.39:saved.tier==='large'?.44:.52,e=this.physics.add.sprite(saved.x,saved.y,texture,row*6).setScale(scale).setDepth(15);saved.row=row;e.dataRef=saved;e.kind=saved.kind;e.tier=saved.tier;e.row=row;e.spawnX=saved.x;e.baseScale=scale;e.nextSkill=0;e.healEnergy=saved.healEnergy||0;e.body.setSize(saved.tier==='small'?140:130,saved.tier==='small'?170:185).setOffset(saved.tier==='small'?58:63,saved.tier==='small'?82:71).setCollideWorldBounds(true).setVelocityX(saved.kind==='healer'?35:-48);e.hpBg=this.add.rectangle(e.x,e.y-75,saved.tier==='boss'?130:72,8,0x250b12,.9).setDepth(24);e.hpBar=this.add.rectangle(e.x-(saved.tier==='boss'?65:36),e.y-75,(saved.tier==='boss'?130:72)*saved.hp/saved.maxHp,6,0xe43d43).setOrigin(0,.5).setDepth(25);e.hpLabel=this.add.text(e.x,e.y-91,`${RPG_MONSTERS[saved.kind].name} ${Math.ceil(saved.hp)}/${saved.maxHp}`,{font:'700 10px "Microsoft YaHei"',color:'#ffd0ce'}).setOrigin(.5).setDepth(25);this.enemyGroup.add(e);this.enemies.push(e);this.wireEnemy(e);this.tweens.add({targets:e,scaleY:{from:scale*.98,to:scale*1.02},duration:700+row*80,yoyo:true,repeat:-1});return e}
  wireEnemy(e){for(const s of this.solids.getChildren())this.physics.add.collider(e,s);for(const p of this.platforms.getChildren())this.physics.add.collider(e,p,null,this.canEnemyLand,this);this.physics.add.overlap(this.player,e,()=>this.touchEnemy(e))}
  refreshWeapon(){this.stats=rpgComputedStats();ensureRpgState().player.hp=Math.min(ensureRpgState().player.hp,this.stats.maxHp);this.weaponFx.removeAll(true);const w=this.stats.weapon;let shape;if(w===RPG_WEAPONS.bow){shape=this.add.arc(0,0,26,-70,70,false,0xc89136).setStrokeStyle(4,0xffdb79)}else if(w===RPG_WEAPONS.dual){shape=this.add.container(0,0,[this.add.rectangle(0,-8,42,5,0xf4d06c).setAngle(-18),this.add.rectangle(0,8,42,5,0xc9e6ff).setAngle(18)])}else{shape=this.add.rectangle(0,0,w===RPG_WEAPONS.greatsword?70:48,w===RPG_WEAPONS.greatsword?9:6,0xe9d497).setStrokeStyle(2,0xffffff).setAngle(-10)}this.weaponFx.add(shape);rpgRenderHud()}
  syncShieldEffect(){const active=ensureRpgState().player.shield;if(active&&!this.shieldFx){const ring=this.add.ellipse(0,0,96,132,0x59e2ff,.07).setStrokeStyle(3,0x8ff5ff,.9),dot1=this.add.circle(0,-65,5,0xd8ffff,1),dot2=this.add.circle(0,65,4,0x62dfff,1);this.shieldFx=this.add.container(this.player.x,this.player.y,[ring,dot1,dot2]).setDepth(28);this.shieldRing=ring;this.shieldDots=[dot1,dot2];this.tweens.add({targets:ring,alpha:{from:.25,to:.8},scale:{from:.95,to:1.06},duration:850,yoyo:true,repeat:-1})}if(!active&&this.shieldFx){this.shieldFx.destroy(true);this.shieldFx=null;this.shieldDots=null}}
  bindControls(){document.querySelectorAll('[data-rpg]').forEach(b=>{const key=b.dataset.rpg,on=()=>rpgInput[key]=true,off=()=>{if(key==='left'||key==='right')rpgInput[key]=false};b.addEventListener('pointerdown',on);b.addEventListener('pointerup',off);b.addEventListener('pointercancel',off)});}
  update(time){if(!this.player?.body||this.soulBattle)return;const r=ensureRpgState(),run=r.run;if(!run)return;const grounded=this.player.body.blocked.down||this.player.body.touching.down,left=this.cursors.left.isDown||this.keys.A.isDown||rpgInput.left,right=this.cursors.right.isDown||this.keys.D.isDown||rpgInput.right;this.player.setAccelerationX(left?-1450:right?1450:0);if(left)this.player.setFlipX(true);if(right)this.player.setFlipX(false);if(grounded)this.jumpCount=0;const jump=Phaser.Input.Keyboard.JustDown(this.cursors.up)||Phaser.Input.Keyboard.JustDown(this.keys.SPACE)||rpgInput.jump;rpgInput.jump=false;if(jump&&this.jumpCount<2){this.jumpCount++;this.player.anims.stop();this.player.setFrame(this.jumpCount===1?12:13);this.player.setVelocityY(this.jumpCount===1?-365:-325);rpgBeep(650,.06)}if(!grounded){this.player.anims.stop();this.player.setFrame(this.player.body.velocity.y<0?12:13)}else if(left||right){if(this.player.anims.currentAnim?.key!=='rpg-run')this.player.play('rpg-run')}else if(this.player.anims.currentAnim?.key!=='rpg-idle')this.player.play('rpg-idle');
    const attack=Phaser.Input.Keyboard.JustDown(this.keys.F)||Phaser.Input.Keyboard.JustDown(this.keys.J)||rpgInput.attack;rpgInput.attack=false;if(attack)this.attack(time);const dodge=Phaser.Input.Keyboard.JustDown(this.keys.K)||rpgInput.dodge;rpgInput.dodge=false;if(dodge)this.dodge(time);for(const [k,i] of [[this.keys.ONE,0],[this.keys.TWO,1],[this.keys.THREE,2]])if(Phaser.Input.Keyboard.JustDown(k))rpgSwitchWeapon(i);for(const [k,i] of [[this.keys.FOUR,0],[this.keys.FIVE,1],[this.keys.SIX,2]])if(Phaser.Input.Keyboard.JustDown(k))rpgUseItem(i);
    this.weaponFx.setPosition(this.player.x+(this.player.flipX?-26:26),this.player.y-2).setScale(this.player.flipX?-1:1,1);if(this.shieldFx){this.shieldFx.setPosition(this.player.x,this.player.y);const a=time*.004;this.shieldDots[0].setPosition(Math.cos(a)*53,Math.sin(a)*70);this.shieldDots[1].setPosition(Math.cos(a+Math.PI)*53,Math.sin(a+Math.PI)*70)}if(this.player.body.velocity.y<0){for(const b of this.blocks||[]){if(b.active&&Math.abs(this.player.x-b.x)<42&&this.player.body.top<=b.y+34&&this.player.body.top>=b.y-10)this.openBlock(b)}}this.updateEnemies(time);for(const p of this.projectiles.getChildren())if(p.active&&Math.abs(p.x-p.originX)>p.range)p.destroy();run.playerX=Math.round(this.player.x);run.playerY=Math.round(this.player.y);if(time%1000<18)rpgPersist();}
  attack(time){
    const stats=rpgComputedStats(),w=stats.weapon,cooldown=1000/(w.rate*stats.attackSpeed);if(time-this.lastAttack<cooldown)return;
    const route=stats.weaponItem.baseId,setEffect=stats.hiddenSetRoutes?.find(x=>x.route===route),legendary=stats.weaponItem.rarity==='legendary';
    this.weaponCasts=(this.weaponCasts||0)+1;const empowered=Boolean(setEffect&&this.weaponCasts%3===0),bonus=(this.nextAttackBonus||1)*(empowered?1+.08*setEffect.rank:1);this.nextAttackBonus=1;
    if(w===RPG_WEAPONS.staff){const free=empowered||legendary&&this.weaponCasts%3===0,cost=free?0:w.manaCost;if(ensureRpgState().player.mana<cost){this.floatText(this.player.x,this.player.y-72,'法力不足',0x68cfff);rpgBeep(120,.09);return}ensureRpgState().player.mana-=cost}
    this.lastAttack=time;this.combo=time-this.comboAt<900?(this.combo%w.combo)+1:1;this.comboAt=time;this.player.anims.stop();this.player.play('rpg-attack',true);const dir=this.player.flipX?-1:1;
    if(w===RPG_WEAPONS.bow||w===RPG_WEAPONS.staff){
      const magic=w===RPG_WEAPONS.staff,y=this.player.body.center.y-8,p=magic?this.add.circle(this.player.x+dir*42,y,14,0x7b5cff,1).setStrokeStyle(4,0xc9f4ff):this.add.ellipse(this.player.x+dir*38,y,25,10,0xf2bd46).setStrokeStyle(2,0xfff2a6);p.setDepth(22);this.physics.add.existing(p);this.projectiles.add(p);p.body.setSize(magic?52:44,magic?52:38).setAllowGravity(false).setVelocityX(dir*(magic?520:650));p.originX=p.x;p.range=w.range*stats.range;p.pierce=magic?(empowered||legendary?3:1):(empowered?4:legendary?3:w.pierce);p.damageMultiplier=w.multiplier*bonus*(legendary?1.12:1);p.hitIds=new Set();if(magic)this.tweens.add({targets:p,scale:{from:.75,to:1.25},alpha:{from:.78,to:1},duration:180,yoyo:true,repeat:-1});this.physics.add.overlap(p,this.enemyGroup,(shot,e)=>{if(!shot.active||!e.active||shot.hitIds.has(e.dataRef.id))return;shot.hitIds.add(e.dataRef.id);this.hitEnemy(e,shot.damageMultiplier,shot.x);if(magic&&(empowered||legendary&&this.weaponCasts%3===0))this.magicBurst(e.x,e.y,shot.damageMultiplier*.55,e.dataRef.id);shot.pierce--;if(shot.pierce<=0)shot.destroy()})
    }else{
      const range=w.range*stats.range,hit=this.add.rectangle(this.player.x+dir*range*.55,this.player.body.center.y,range,112,0xffcf58,.08).setDepth(21);this.physics.add.existing(hit);hit.body.setAllowGravity(false);for(const e of this.enemies.filter(x=>x.active)){const dx=(e.x-this.player.x)*dir;if(dx>=-12&&dx<=range+28&&Math.abs(e.body.center.y-this.player.body.center.y)<110)this.hitEnemy(e,w.multiplier*bonus,hit.x)}this.time.delayedCall(125,()=>hit.destroy());this.tweens.add({targets:hit,alpha:0,scaleY:1.4,duration:120});
      if((legendary||setEffect)&&w===RPG_WEAPONS.sword&&this.combo===3)this.launchSwordWave(dir,setEffect?.rank||5);
      if(setEffect&&w===RPG_WEAPONS.greatsword)this.magicBurst(this.player.x+dir*90,this.player.y,w.multiplier*.38*bonus,'',0xffc35a);
    }
    rpgRenderHud();rpgPersist();rpgBeep(w===RPG_WEAPONS.greatsword?180:w===RPG_WEAPONS.staff?520:760,.07)
  }
  launchSwordWave(dir,rank=3){const wave=this.add.rectangle(this.player.x+dir*45,this.player.body.center.y,54,16,0xffda62,.75).setDepth(22);this.physics.add.existing(wave);this.projectiles.add(wave);wave.body.setAllowGravity(false).setVelocityX(dir*520);wave.originX=wave.x;wave.range=430+rank*24;wave.pierce=2;wave.damageMultiplier=.62+rank*.04;wave.hitIds=new Set();this.physics.add.overlap(wave,this.enemyGroup,(shot,e)=>{if(shot.hitIds.has(e.dataRef.id))return;shot.hitIds.add(e.dataRef.id);this.hitEnemy(e,shot.damageMultiplier,shot.x);if(--shot.pierce<=0)shot.destroy()})}
  magicBurst(x,y,multiplier,excludeId='',color=0x8d6bff){const ring=this.add.circle(x,y,18,color,.18).setStrokeStyle(5,0xe5f7ff,.95).setDepth(23);for(const e of this.enemies.filter(x=>x.active&&x.dataRef.id!==excludeId))if(Phaser.Math.Distance.Between(x,y,e.x,e.y)<125)this.hitEnemy(e,multiplier,x);this.tweens.add({targets:ring,scale:6,alpha:0,duration:260,onComplete:()=>ring.destroy()})}
  dodge(time){const stats=rpgComputedStats(),cd=stats.dodgeCooldown*(this.buffs.speed?.active?.8:1);if(time-this.lastDodge<cd)return;this.lastDodge=time;this.invulnerableUntil=Date.now()+220;const dir=this.player.flipX?-1:1;this.player.setVelocityX(dir*430);this.player.setAlpha(.35);const dualSet=stats.hiddenSetRoutes?.find(x=>x.route==='dual');if(stats.weaponItem.rarity==='legendary'&&stats.weaponItem.baseId==='dual'||dualSet&&stats.weaponItem.baseId==='dual')this.forceCritHits=Math.max(this.forceCritHits||0,dualSet?Math.min(3,1+Math.floor(dualSet.rank/2)):3);if(stats.legendaryIds.includes('boots'))this.nextAttackBonus=1.4;const ghost=this.add.sprite(this.player.x,this.player.y,this.player.texture.key,this.player.frame.name).setScale(this.player.scaleX,this.player.scaleY).setAlpha(.45).setTint(0x83e9ff).setDepth(19);this.tweens.add({targets:ghost,alpha:0,x:ghost.x-dir*40,duration:320,onComplete:()=>ghost.destroy()});this.time.delayedCall(320,()=>this.player?.setAlpha(1));rpgBeep(980,.06)}
  hitEnemy(e,multiplier,fromX){if(!e?.active||!e.dataRef?.alive)return;const ref=e.dataRef;if(ref.kind==='guardian'&&Math.random()<.25){this.floatText(e.x,e.y-70,'格挡',0x72bfff);return}const stats=rpgComputedStats(),forced=(this.forceCritHits||0)>0,damage=rpgDamageValue(stats.attack*(this.buffs.polish?.active?1.25:1),multiplier,ref.defense,forced?1:stats.crit);if(forced)this.forceCritHits--;ref.hp=Math.max(0,ref.hp-damage.amount);if(stats.weaponItem.rarity==='legendary'&&stats.weaponItem.baseId==='greatsword'){ref.defense=Math.max(0,ref.defense-2);e.nextSkill+=1200}e.setTint(0xff6969);e.setVelocityX(e.x<fromX?-120:120);this.time.delayedCall(130,()=>e?.clearTint());this.floatText(e.x,e.y-60,`${damage.crit?'暴击 ':''}-${damage.amount}`,damage.crit?0xffd45a:0xffffff);this.updateEnemyBar(e);if(ref.hp<=0)this.physicalDefeat(e)}
  updateEnemyBar(e){const ref=e.dataRef,w=ref.tier==='boss'?130:72;e.hpBar.width=w*Math.max(0,ref.hp/ref.maxHp);e.hpLabel.setText(`${RPG_MONSTERS[ref.kind].name} ${Math.ceil(ref.hp)}/${ref.maxHp}`)}
  physicalDefeat(e){const ref=e.dataRef;e.disableBody(true,true);e.hpBg.destroy();e.hpBar.destroy();e.hpLabel.destroy();if(ref.hasSoul&&!ref.soulResolved){this.spawnSoul(ref,e.x,e.y);return}this.finishEnemy(ref,false)}
  spawnSoul(ref,x,y){const row=ref.kind==='ranged'?1:ref.kind==='large'?2:ref.kind==='healer'?3:ref.kind==='boss'?1:0,s=this.add.sprite(x,y-8,'rpg-soul',row*6).setScale(ref.tier==='boss'?.5:ref.tier==='large'?.44:.36).setDepth(30).setAlpha(.9);s.setBlendMode(Phaser.BlendModes.ADD);this.tweens.add({targets:s,y:y-90,alpha:{from:.25,to:1},duration:700,ease:'Back.out',onComplete:()=>{this.physics.pause();this.soulBattle={enemy:ref,sprite:s,attempts:this.run.attempts[ref.id]||0};rpgOpenSoulBattle(ref)}});for(let i=0;i<9;i++){const p=this.add.circle(x+(i-4)*7,y,2+i%2,0x8ff5ff,.8).setDepth(29);this.tweens.add({targets:p,y:y-100-i*4,x:p.x+(i%2?20:-20),alpha:0,duration:650+i*35,onComplete:()=>p.destroy()})}rpgBeep(1180,.2)}
  finishEnemy(ref,soul){ref.alive=false;ref.soulResolved=soul||ref.soulResolved;const loot=rpgRollMonsterLoot(ref,this.run);rpgAddRunReward(loot);this.showLoot(ref,loot);if(ref.id==='boss')this.completeRun();rpgRenderHud();rpgPersist()}
  showLoot(ref,loot){const color=loot.items[0]?rpgRarity(loot.items[0]).color:'#f0ca6d',text=`+${loot.coins}金币 +${loot.xp}经验${loot.items.length?' · '+loot.items.map(x=>x.name).join('、'):''}`;this.floatText(Math.min(ref.x,6000),360,text,Phaser.Display.Color.HexStringToColor(color).color)}
  touchEnemy(e){if(Date.now()<this.invulnerableUntil||Date.now()-this.lastDamage<900)return;this.damagePlayer(e.dataRef.attack,e.x)}
  damagePlayer(amount,fromX){const r=ensureRpgState(),stats=rpgComputedStats(),now=Date.now();if(now<this.invulnerableUntil||now-this.lastDamage<650)return;if(r.player.shield){r.player.shield=false;this.lastDamage=now;this.invulnerableUntil=now+650;this.floatText(this.player.x,this.player.y-60,'护盾抵挡',0x7cecff);this.breakShield();rpgRenderHud();return}const damage=Math.max(1,Math.round(amount*100/(100+stats.defense))),lethal=r.player.hp-damage<=0,checkpoint=this.run?.checkpoint?.id||'cp0';if(lethal&&stats.legendaryIds.includes('chest')&&this.run?.chestSavedAt!==checkpoint){r.player.hp=1;r.player.shield=true;this.run.chestSavedAt=checkpoint;this.syncShieldEffect();this.floatText(this.player.x,this.player.y-70,'馆藏守护：保留1点生命',0xffd36c)}else r.player.hp=Math.max(0,r.player.hp-damage);this.lastDamage=now;this.invulnerableUntil=now+650;this.player.setTint(0xff5050).setVelocityX(this.player.x<fromX?-240:240).setVelocityY(-170);this.time.delayedCall(280,()=>this.player?.clearTint());this.floatText(this.player.x,this.player.y-65,`-${damage}`,0xff5656);rpgRenderHud();if(r.player.hp<=0)this.failToCheckpoint();rpgPersist()}
  breakShield(){const wave=this.add.ellipse(this.player.x,this.player.y,80,116,0x5ddfff,.1).setStrokeStyle(5,0xb9f8ff).setDepth(30);if(this.shieldRing)this.shieldRing.setStrokeStyle(8,0xffffff,1);this.tweens.add({targets:wave,scale:2.2,alpha:0,duration:400,onComplete:()=>wave.destroy()});this.time.delayedCall(90,()=>this.syncShieldEffect())}
  updateEnemies(time){for(const e of this.enemies){if(!e.active)continue;const ref=e.dataRef;e.hpBg.setPosition(e.x,e.y-75);e.hpBar.setPosition(e.x-(ref.tier==='boss'?65:36),e.y-75);e.hpLabel.setPosition(e.x,e.y-91);if(ref.kind==='healer'){e.healEnergy=Math.min(100,e.healEnergy+(time>e.nextSkill?1.1:0));if(e.healEnergy>=100&&time>e.nextSkill&&!e.silencedUntil){const target=this.enemies.filter(x=>x.active&&['large','boss'].includes(x.dataRef.tier)&&x.dataRef.hp<x.dataRef.maxHp).sort((a,b)=>a.dataRef.hp-b.dataRef.hp)[0];if(target){target.dataRef.hp=Math.min(target.dataRef.maxHp,target.dataRef.hp+target.dataRef.maxHp*.12);this.updateEnemyBar(target);this.floatText(target.x,target.y-120,'治疗 +12%',0x71f3a7);e.healEnergy=0;e.nextSkill=time+5000}}continue}let vx=e.body.velocity.x||48;if(Math.abs(e.x-e.spawnX)>190)vx=e.x>e.spawnX?-Math.abs(vx):Math.abs(vx);if(ref.kind==='berserker'&&Math.abs(this.player.x-e.x)<260&&time>e.nextSkill){vx=this.player.x<e.x?-210:210;e.nextSkill=time+2400}if(ref.kind==='ranged'&&Math.abs(this.player.x-e.x)<520&&time>e.nextSkill){this.enemyShot(e);e.nextSkill=time+2100}if(ref.kind==='boss'){const ratio=ref.hp/ref.maxHp,newPhase=ratio<=.35?3:ratio<=.7?2:1;if(newPhase!==ref.phase){ref.phase=newPhase;this.floatText(e.x,e.y-135,`阶段 ${newPhase}`,0xffa354)}if(time>e.nextSkill){this.bossSkill(e,ref.phase);e.nextSkill=time+Math.max(900,2300-ref.phase*350)}}e.setVelocityX(vx).setFlipX(vx>0)}for(const shot of this.enemyShots.getChildren())if(shot.active&&Math.abs(shot.x-shot.originX)>560)shot.destroy()}
  enemyShot(e,speed=225,color=0xf05d58,damageScale=1){const dir=this.player.x<e.x?-1:1,s=this.add.circle(e.x+dir*25,e.y-5,7,color).setStrokeStyle(2,0xffd3c7).setDepth(19);this.tweens.add({targets:e,x:e.x-dir*13,duration:90,yoyo:true});this.physics.add.existing(s);this.enemyShots.add(s);s.body.setAllowGravity(false).setVelocityX(dir*speed);s.originX=s.x;s.damage=e.dataRef.attack*damageScale;rpgBeep(155,.07)}
  bossSkill(e,phase){const map=this.node.mapId;if(map==='gallery'){for(let i=0;i<phase;i++)this.time.delayedCall(i*150,()=>this.enemyShot(e,210+i*35,0xe9a94a,1))}else if(map==='blueprint'){const warning=this.add.rectangle(this.player.x,492,170+phase*35,18,0x62c7ff,.5).setDepth(20);this.time.delayedCall(520,()=>{const x=warning.x;warning.destroy();const wall=this.add.rectangle(x,410,45,170,0x72d9ff,.65).setDepth(21);this.tweens.add({targets:wall,alpha:0,y:350,duration:450,onComplete:()=>wall.destroy()});if(Math.abs(this.player.x-x)<90)this.damagePlayer(e.dataRef.attack*1.2,e.x)})}else if(map==='garden'){e.setVelocityX(this.player.x<e.x?-260-phase*35:260+phase*35);if(phase>1)this.enemyShot(e,170,0x82d86f,.85)}else if(map==='cathedral'){for(let i=0;i<phase+1;i++)this.time.delayedCall(i*110,()=>this.enemyShot(e,245,0xffd86e,1))}else{const weapon=rpgComputedStats().weapon;if(weapon===RPG_WEAPONS.bow)this.enemyShot(e,360,0xe870ff,1.15);else{const warning=this.add.rectangle(this.player.x,495,130+phase*30,12,0xff49bd,.55).setDepth(20);this.time.delayedCall(450,()=>{const x=warning.x;warning.destroy();if(Math.abs(this.player.x-x)<85+phase*10)this.damagePlayer(e.dataRef.attack*1.35,e.x)})}}}
  soulPlayerAttack(target){const bolt=this.add.rectangle(this.player.x,this.player.y-15,50,9,0xffd25b,1).setStrokeStyle(2,0xffffff).setDepth(60);this.tweens.add({targets:bolt,x:target.x,y:target.y,duration:260,ease:'Cubic.in',onComplete:()=>{bolt.destroy();target.setTint(0xff6b6b);this.cameras.main.shake(120,.006);this.time.delayedCall(150,()=>target?.clearTint())}})}
  soulEnemyAttack(source,amount){const orb=this.add.circle(source.x,source.y,12,0xf04455,1).setStrokeStyle(3,0xffd0c7).setDepth(60);this.tweens.add({targets:source,x:source.x+(this.player.x<source.x?-24:24),duration:100,yoyo:true});this.tweens.add({targets:orb,x:this.player.x,y:this.player.y,duration:280,ease:'Cubic.in',onComplete:()=>{orb.destroy();if(amount>0)this.damagePlayer(amount,source.x)}})}
  createBlocks(){this.blocks=[];for(let i=0;i<10;i++){if(this.run.openedBlocks.includes(`q${i}`))continue;const x=620+i*510,y=235+(i%2)*90,b=this.add.rectangle(x,y,48,48,0xd8b763).setStrokeStyle(4,0x68491f).setDepth(12),mark=this.add.text(x,y,'?',{font:'900 28px monospace',color:'#102331'}).setOrigin(.5).setDepth(13);this.physics.add.existing(b,true);b.blockId=`q${i}`;b.mark=mark;this.blocks.push(b);this.physics.add.overlap(this.projectiles,b,(p,block)=>{p.destroy();this.openBlock(block)})}}
  openBlock(b){if(!b?.active)return;this.run.openedBlocks.push(b.blockId);const r=ensureRpgState(),reward=Math.abs(rpgHash(`${this.run.seed}-${b.blockId}`))%5;if(reward===0)r.player.hp=Math.min(rpgComputedStats().maxHp,r.player.hp+rpgComputedStats().maxHp*.25);if(reward===1){if(r.player.shield)r.consumables.hint++;else r.player.shield=true}if(reward===2)r.consumables.hint++;if(reward===3)r.consumables.potion++;if(reward===4)r.player.coins+=25*this.node.id;b.mark.destroy();b.setFillStyle(0x4c4337,.8);b.setStrokeStyle(3,0x766c5b);b.body.enable=false;this.tweens.add({targets:b,y:b.y-18,duration:100,yoyo:true});this.floatText(b.x,b.y-45,reward===1&&r.player.shield?'护盾已生效':'奖励已获得',0xffd66f);this.syncShieldEffect();rpgRenderHud();rpgPersist()}
  createCheckpoints(){this.checkpoints=this.physics.add.staticGroup();[120,1900,3800,5550].forEach((x,i)=>{const active=this.run.checkpoints.includes(`cp${i}`),base=this.add.rectangle(x,443,54,78,active?0x43d3a6:0xb18a45,.75).setStrokeStyle(3,active?0x9affdf:0xffdc87).setDepth(10);this.physics.add.existing(base,true);base.cpId=`cp${i}`;this.checkpoints.add(base);this.add.text(x,392,'展厅记录台',{font:'700 12px "Microsoft YaHei"',color:active?'#9affdf':'#ffe2a1'}).setOrigin(.5).setDepth(11);this.physics.add.overlap(this.player,base,()=>this.activateCheckpoint(base))})}
  activateCheckpoint(cp){if(this.run.checkpoints.includes(cp.cpId))return;const r=ensureRpgState();this.run.checkpoints.push(cp.cpId);this.run.checkpoint={id:cp.cpId,x:cp.x,hp:r.player.hp,enemySnapshot:this.run.enemies.map(e=>({id:e.id,hp:e.hp,alive:e.alive,soulResolved:e.soulResolved}))};cp.setFillStyle(0x43d3a6,.9);this.floatText(cp.x,370,'已记录当前位置',0x8fffd8);rpgPersist()}
  createRooms(){const rooms=[['painting',1450,330,'隐藏画室'],['repair',3020,330,'奖励修复室'],['sculpture',4580,250,'隐藏雕塑室']];this.roomPortals=[];for(const [id,x,y,label] of rooms){const door=this.add.rectangle(x,y,55,96,0x4c334f,.55).setStrokeStyle(3,0x8defff).setDepth(9);this.physics.add.existing(door,true);door.roomId=id;door.opened=this.run.openedRooms.includes(id);this.add.text(x,y-65,label,{font:'700 13px "Microsoft YaHei"',color:'#9defff'}).setOrigin(.5).setDepth(10);this.roomPortals.push(door);if(id==='painting')this.physics.add.overlap(this.projectiles,door,(p,d)=>{p.destroy();this.enterRoom(d)});else this.physics.add.overlap(this.player,door,()=>{if(id!=='repair'||this.run.collected.length>=6||this.run.enemies.filter(e=>!e.alive).length>=4)this.enterRoom(door)})}const roomXs={painting:6350,repair:6750,sculpture:7150};for(const [id,x] of Object.entries(roomXs)){this.makeSolid(x-170,470,340,40);this.add.rectangle(x,300,320,250,id==='repair'?0x8a6128:0x264c5b,.35).setStrokeStyle(3,0xd8b66b).setDepth(2);this.add.text(x,205,id==='painting'?'秘密画室':id==='repair'?'展品修复台':'雕塑密藏',{font:'700 22px "Microsoft YaHei"',color:'#f7d994'}).setOrigin(.5).setDepth(8);const exit=this.add.rectangle(x+130,420,34,70,0x5edbc1,.65).setDepth(10);this.physics.add.existing(exit,true);this.physics.add.overlap(this.player,exit,()=>this.player.setPosition(id==='painting'?1510:id==='repair'?3080:4640,410));for(let i=0;i<3;i++){const star=this.add.star(x-90+i*90,350,5,6,13,0xf5cc5b).setStrokeStyle(2,0xffffff).setDepth(12);this.physics.add.existing(star,true);star.rewardId=`${id}-${i}`;this.physics.add.overlap(this.player,star,()=>this.collectRoomReward(star,id))}}}
  enterRoom(door){if(!door?.active)return;if(!this.run.openedRooms.includes(door.roomId))this.run.openedRooms.push(door.roomId);const x={painting:6350,repair:6750,sculpture:7150}[door.roomId];this.player.setPosition(x,390);if(door.roomId==='repair')this.time.delayedCall(300,()=>rpgOpenRepairChoice());rpgPersist()}
  collectRoomReward(star,id){if(!star.active||this.run.collected.includes(star.rewardId))return;this.run.collected.push(star.rewardId);const r=ensureRpgState();if(id==='painting')r.consumables.hint++;if(id==='sculpture')r.player.shield=true;if(id==='repair')r.player.coins+=30*this.node.id;star.destroy();rpgRenderHud();rpgPersist()}
  applyBuff(id,duration){this.buffs[id]={active:true,until:this.time.now+duration};this.time.delayedCall(duration,()=>{if(this.buffs[id])this.buffs[id].active=false})}
  silenceHealers(){for(const e of this.enemies.filter(x=>x.active&&x.kind==='healer')){e.silencedUntil=this.time.now+5000;e.healEnergy=0;this.floatText(e.x,e.y-80,'沉默',0x9aeaff)}}
  failToCheckpoint(){const r=ensureRpgState(),lost=Math.round((this.run.earnedCoins||0)*.2);r.player.coins=Math.max(0,r.player.coins-lost);r.player.hp=Math.max(1,this.run.checkpoint.hp||rpgComputedStats().maxHp*.5);this.player.setPosition(this.run.checkpoint.x,410).setVelocity(0,0);for(const snap of this.run.checkpoint.enemySnapshot||[]){const ref=this.run.enemies.find(x=>x.id===snap.id);if(ref){ref.hp=snap.hp;ref.alive=snap.alive;ref.soulResolved=snap.soulResolved}}for(const e of this.enemies){e.hpBg?.destroy();e.hpBar?.destroy();e.hpLabel?.destroy();e.destroy()}this.enemyGroup.clear(true,true);this.enemies=[];for(const ref of this.run.enemies.filter(x=>x.alive))this.spawnEnemy(ref);this.floatText(this.player.x,330,`记录点复活 · 损失${lost}金币`,0xff7b72);rpgRenderHud();rpgPersist()}
  completeRun(){const r=ensureRpgState(),node=rpgCurrentNode(),elapsed=(Date.now()-new Date(this.run.startedAt).getTime())/1000;this.run.status='completed';this.run.stars=1+(r.player.hp/rpgComputedStats().maxHp>=.5?1:0)+(this.run.soulsAnswered.length>=10?1:0);node.firstClear=true;node.status='completed';node.stars=Math.max(node.stars,this.run.stars);node.bestTime=node.bestTime?Math.min(node.bestTime,elapsed):elapsed;if(node.id===r.route.unlocked&&r.route.unlocked<88){r.route.unlocked++;rpgEnsureNodes(r.route.unlocked)}this.physics.pause();this.scene.pause();r.run=null;rpgPersist();rpgShowResult(node,node.stars)}
  floatText(x,y,text,color=0xffffff){const t=this.add.text(x,y,text,{font:'800 15px "Microsoft YaHei"',color:'#'+color.toString(16).padStart(6,'0'),stroke:'#07131f',strokeThickness:4}).setOrigin(.5).setDepth(50);this.tweens.add({targets:t,y:y-45,alpha:0,duration:950,onComplete:()=>t.destroy()})}
}

function rpgQuestionForEnemy(ref){const node=rpgCurrentNode(),questions=rpgQuestionsForNode(node,Boolean(ensureRpgState().run?.replay));return questions.find(x=>x.id===ref.questionId)||questions[0]}
function rpgOpenSoulBattle(ref){const scene=rpgScene,battle=scene.soulBattle,item=rpgQuestionForEnemy(ref),parts=gameV2SemanticSegments(item),others=rpgQuestionsForNode(rpgCurrentNode(),Boolean(scene.run.replay)).filter(x=>x.id!==item.id).flatMap(gameV2SemanticSegments),options=rpgShuffle([...new Set([...parts,...others])].slice(0,Math.max(parts.length+5,9)),`${scene.run.seed}-${ref.id}-${battle.attempts}`);battle.item=item;battle.expected=parts;battle.selected=[];battle.options=options;battle.hint='';rpgRenderSoulBattle()}
function rpgRenderSoulBattle(){const scene=rpgScene,b=scene?.soulBattle;if(!b)return;const item=b.item,policy=answerOrderPolicy(item),segments=gameV2SemanticSegments(item),attemptsLeft=3-b.attempts,host=document.getElementById('rpgModal');host.innerHTML=`<section class="soul-battle"><div class="soul-stage"><div class="soul-portrait row-${b.enemy.row||0}"></div><div><small>${escapeHtml(item.chapter||'艺术概论')} · ${policy==='strict'?'按语意顺序':'意思完整，顺序不限'}</small><h2>${escapeHtml(item.q)}</h2><p>灵魂机会 ${'◆'.repeat(attemptsLeft)}${'◇'.repeat(3-attemptsLeft)}</p></div></div><div class="soul-slots">${segments.map((_,i)=>`<button onclick="rpgRemoveSoulPart(${i})"><span>${i+1}</span>${escapeHtml(b.selected[i]||'____________')}</button>`).join('')}</div><div class="soul-options">${b.options.map((o,i)=>`<button class="${b.hint===o?'hint-pulse':''}" onclick="rpgSelectSoulPart(${i})" ${b.selected.includes(o)?'disabled':''}>${escapeHtml(o)}</button>`).join('')}</div><div class="soul-feedback">${b.feedback?escapeHtml(b.feedback):'击败灵魂才能获得高阶奖励。'}</div><footer><button onclick="rpgUseSoulHint()">提示</button><button class="attack" onclick="rpgSubmitSoul()" ${b.selected.length===segments.length?'':'disabled'}>提交灵魂攻击</button></footer></section>`}
function rpgSelectSoulPart(index){const b=rpgScene?.soulBattle;if(!b||b.selected.length>=b.expected.length)return;b.selected.push(b.options[index]);rpgRenderSoulBattle()}
function rpgRemoveSoulPart(index){const b=rpgScene?.soulBattle;if(!b)return;b.selected.splice(index,1);rpgRenderSoulBattle()}
function rpgUseSoulHint(){const r=ensureRpgState(),b=rpgScene?.soulBattle;if(!b)return;const free=rpgComputedStats().legendaryIds.includes('helmet')&&!b.freeLegendaryHint;if(!free&&!r.consumables.hint){notify('提示卡不足');return}const eligible=b.expected.find(x=>!b.selected.includes(x));if(!eligible)return;if(free)b.freeLegendaryHint=true;else r.consumables.hint--;b.hint=eligible;rpgRenderSoulBattle();rpgRenderHud();rpgPersist()}
function rpgSubmitSoul(){const scene=rpgScene,b=scene?.soulBattle;if(!b)return;const correct=maskAnswerCorrect(b.item,b.selected,b.expected);if(correct){b.feedback='✓ 回答正确，灵魂被击碎';rpgRenderSoulBattle();const ref=b.enemy;ref.soulResolved=true;ref.alive=false;scene.run.soulsAnswered.push(ref.questionId);scene.soulPlayerAttack(b.sprite);scene.tweens.add({targets:b.sprite,alpha:0,scale:.1,y:b.sprite.y-80,delay:220,duration:500,onComplete:()=>b.sprite.destroy()});scene.time.delayedCall(820,()=>{document.getElementById('rpgModal').innerHTML='';scene.soulBattle=null;scene.finishEnemy(ref,true);scene.physics.resume()});const r=ensureRpgState(),bracer=rpgItemById(r.equipment.bracer);if(bracer?.rarity==='legendary')r.player.legendaryStacks=Math.min(3,(r.player.legendaryStacks||0)+1);rpgBeep(1180,.2);return}
  b.attempts++;scene.run.attempts[b.enemy.id]=b.attempts;scene.run.wrongSouls.push(b.item.id);if(typeof markWrong==='function')markWrong(typeof getQuestion==='function'?(getQuestion(b.item.id)||b.item):b.item);if(b.attempts>=3){const r=ensureRpgState(),stats=rpgComputedStats();r.player.hp=Math.max(1,r.player.hp-stats.maxHp*.3);b.enemy.hp=Math.max(1,Math.round(b.enemy.maxHp*.3));b.enemy.alive=true;b.feedback='× 三次失败：玩家失去30%生命，怪物以30%生命复活';rpgRenderSoulBattle();scene.soulEnemyAttack(b.sprite,0);scene.time.delayedCall(1100,()=>{b.sprite.destroy();document.getElementById('rpgModal').innerHTML='';scene.soulBattle=null;scene.spawnEnemy(b.enemy);scene.physics.resume();rpgRenderHud();rpgPersist()});return}scene.soulEnemyAttack(b.sprite,Math.max(6,b.enemy.attack*.65));b.feedback=`× 回答错误：灵魂反击，还剩 ${3-b.attempts} 次机会`;b.selected=[];b.options=rpgShuffle(b.options,`${scene.run.seed}-${b.enemy.id}-${b.attempts}`);b.hint='';rpgRenderSoulBattle();rpgPersist()}
function rpgOpenRepairChoice(){const host=document.getElementById('rpgModal');if(!host||ensureRpgState().run?.repairChosen)return;host.innerHTML=`<section class="repair-choice"><small>奖励修复室</small><h2>选择一种修复成果</h2><div><button onclick="rpgChooseRepair('heal')">✚<b>生命修复</b><span>恢复35%生命</span></button><button onclick="rpgChooseRepair('shield')">◉<b>能量护盾</b><span>抵挡一次攻击</span></button><button onclick="rpgChooseRepair('hint')">?<b>知识提示</b><span>获得1张提示卡</span></button></div></section>`}
function rpgChooseRepair(choice){const r=ensureRpgState(),stats=rpgComputedStats();if(choice==='heal')r.player.hp=Math.min(stats.maxHp,r.player.hp+stats.maxHp*.35);if(choice==='shield'){if(r.player.shield)r.consumables.hint++;else r.player.shield=true}if(choice==='hint')r.consumables.hint++;r.run.repairChosen=choice;document.getElementById('rpgModal').innerHTML='';rpgScene?.syncShieldEffect();rpgRenderHud();rpgPersist()}
function rpgShowResult(node,stars){const host=document.getElementById('rpgModal');if(host)host.innerHTML=`<section class="rpg-result"><small>第${node.id}关完成</small><h2>${escapeHtml(node.mapName)}</h2><div>${'★'.repeat(stars)}${'☆'.repeat(3-stars)}</div><p>新节点已经加入冒险路线。旧关可以继续刷装备和错题。</p><button onclick="rpgExitGame()">返回冒险路线</button></section>`}

const rpgBaseCourseView=courseView,rpgBaseRender=render;
courseView=rpgCourseView;
render=function(){ensureRpgState();if(state.view!=='rpgGame')document.body.classList.remove('rpg-mode');if(state.view==='rpgRoute'){content.innerHTML=rpgRouteView()}else if(state.view==='rpgInventory'){content.innerHTML=rpgInventoryView()}else if(state.view==='rpgGame'){document.body.classList.add('rpg-mode');content.innerHTML=rpgGameView()}else{rpgBaseRender()}document.querySelectorAll('.nav-item,.mobile-nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));const streak=document.getElementById('streakSide');if(streak)streak.textContent=state.streak+' 天'};
if(isRpgTest()){const testRpg=ensureRpgState();testRpg.route.current=1;testRpg.run=null;state.view='rpgGame'}
render();
window.__RPG_TEST__={state:()=>JSON.parse(JSON.stringify(ensureRpgState())),launch:()=>rpgLaunch(),scene:()=>rpgScene,snapshot:()=>({player:rpgScene?.player?{x:rpgScene.player.x,y:rpgScene.player.y,frame:rpgScene.player.frame.name}:null,enemies:rpgScene?.run?.enemies||[],map:rpgCurrentNode().mapId,route:ensureRpgState().route,stats:rpgComputedStats(),run:rpgScene?.run||null}),attack:(id)=>{const e=rpgScene?.enemies.find(x=>x.dataRef.id===id&&x.active);if(e){e.dataRef.hp=1;rpgScene.hitEnemy(e,10,e.x-50)}},soulCorrect:()=>{const b=rpgScene?.soulBattle;if(b){b.selected=[...b.expected];rpgSubmitSoul()}},soulWrong:()=>{const b=rpgScene?.soulBattle;if(b){b.selected=b.options.filter(x=>!b.expected.includes(x)).slice(0,b.expected.length);while(b.selected.length<b.expected.length)b.selected.push('__错__');rpgSubmitSoul()}},teleport:(x,y=420)=>rpgScene?.player?.setPosition(x,y),checkpoint:()=>rpgScene?.activateCheckpoint(rpgScene?.checkpoints?.getChildren()[1])};
