/* RPG第七版：88关路线、法力施法、实体掉落、图像化装备栏与套装实效。 */
const RPG_V6_WORLD_END=4380;
const RPG_V6_ITEM_ATLASES={weapon:'rpg-weapons-v2',gear:'rpg-gear-consumables-v2'};
const RPG_V6_SET_ATLASES={plain:'rpg-set-plain-v1',common:'rpg-set-common-v1',excellent:'rpg-set-excellent-v1',fine:'rpg-set-fine-v1',mythic:'rpg-set-mythic-v1',legendary:'rpg-set-legendary-v1'};
const RPG_V6_HERO_ATLASES={plain:'rpg-hero-set-plain-v1',common:'rpg-hero-set-common-v1',excellent:'rpg-hero-set-excellent-v1',fine:'rpg-hero-set-fine-v1',mythic:'rpg-hero-set-mythic-v1',legendary:'rpg-hero-set-legendary-v1'};
const RPG_V6_ICON_META={
  sword:{atlas:'weapon',index:0,cols:5,rows:1},greatsword:{atlas:'weapon',index:1,cols:5,rows:1},dual:{atlas:'weapon',index:2,cols:5,rows:1},bow:{atlas:'weapon',index:3,cols:5,rows:1},staff:{atlas:'weapon',index:4,cols:5,rows:1},
  helmet:{atlas:'gear',index:0,cols:7,rows:2},chest:{atlas:'gear',index:1,cols:7,rows:2},bracer:{atlas:'gear',index:2,cols:7,rows:2},boots:{atlas:'gear',index:3,cols:7,rows:2},potion:{atlas:'gear',index:4,cols:7,rows:2},mana:{atlas:'gear',index:5,cols:7,rows:2},shield:{atlas:'gear',index:6,cols:7,rows:2},speed:{atlas:'gear',index:7,cols:7,rows:2},polish:{atlas:'gear',index:8,cols:7,rows:2},lens:{atlas:'gear',index:9,cols:7,rows:2},silence:{atlas:'gear',index:10,cols:7,rows:2},hint:{atlas:'gear',index:11,cols:7,rows:2},coins:{atlas:'gear',index:12,cols:7,rows:2},dust:{atlas:'gear',index:13,cols:7,rows:2}
};
const RPG_V6_STAGE_SPLITS=[{start:0,count:10}];

function rpgV6IconKey(value){
  if(!value)return'';
  if(typeof value==='string')return RPG_V6_ICON_META[value]!==undefined?value:(rpgItemById(value)?.baseId||'');
  return value.baseId||value.slot||'';
}
function rpgV6IconMarkup(value,className=''){
  if(typeof value==='object'&&value?.visual&&RPG_V6_SET_ATLASES[value.visual.atlas]){const atlas=value.visual.atlas,row=Math.max(0,Math.min(4,value.visual.row||0)),col=Math.max(0,Math.min(4,value.visual.col||0));return`<i class="rpg-item-icon ${className}" style="--icon-image:url('assets/art/rpg-set-${atlas}-v1.png');--icon-size-x:500%;--icon-size-y:500%;--icon-x:${col*25}%;--icon-y:${row*25}%" aria-hidden="true"></i>`}
  const key=rpgV6IconKey(value),meta=RPG_V6_ICON_META[key];if(!meta)return`<i class="rpg-item-icon is-empty ${className}" aria-hidden="true"></i>`;
  const col=meta.index%meta.cols,row=Math.floor(meta.index/meta.cols),x=meta.cols===1?0:col/(meta.cols-1)*100,y=meta.rows===1?0:row/(meta.rows-1)*100,file=meta.atlas==='weapon'?'rpg-weapons-v2.png':'rpg-gear-consumables-v2.png';
  return`<i class="rpg-item-icon ${className}" style="--icon-image:url('assets/art/${file}');--icon-size-x:${meta.cols*100}%;--icon-size-y:${meta.rows*100}%;--icon-x:${x}%;--icon-y:${y}%" aria-hidden="true"></i>`;
}
function rpgV6StageSplit(){return RPG_V6_STAGE_SPLITS[0]}
function rpgV6SoulTarget(node){return rpgV6StageSplit(node).count}
function rpgV6HeroAppearance(){
  const r=ensureRpgState(),stats=rpgComputedStats(),weapon=stats.weaponItem||rpgStarterSword(),armor=['helmet','chest','bracer','boots'].map(slot=>rpgItemById(r.equipment[slot])).filter(Boolean),rarityCounts={};
  for(const item of armor)rarityCounts[item.rarity]=(rarityCounts[item.rarity]||0)+1;
  const dominant=Object.entries(rarityCounts).sort((a,b)=>b[1]-a[1]||((RPG_RARITIES.find(x=>x.id===b[0])?.rank||0)-(RPG_RARITIES.find(x=>x.id===a[0])?.rank||0)))[0];
  const rarity=dominant&&dominant[1]>=3&&RPG_V6_HERO_ATLASES[dominant[0]]?dominant[0]:(RPG_V6_HERO_ATLASES[weapon.rarity]?weapon.rarity:'plain'),route=RPG_SET_ROWS[weapon.baseId]===undefined?'sword':weapon.baseId,row=RPG_SET_ROWS[route];
  return{rarity,route,row,atlas:RPG_V6_HERO_ATLASES[rarity],key:`rpg-worn-${rarity}-${row}`};
}

const rpgV6BaseQuestionsForNode=rpgQuestionsForNode;
rpgQuestionsForNode=function(node,replay=false){
  let questions=rpgV6BaseQuestionsForNode(node,replay);
  if(!questions.length&&node.id!==1)questions=rpgV6BaseQuestionsForNode(rpgNode(1),replay);
  if(!questions.length){const task=ensureDailyTask();questions=(task.items||[]).slice(0,10).map(x=>({id:x.id,q:x.q,answerText:x.answerText,chapter:x.chapter,section:x.section,orderPolicy:answerOrderPolicy(x)}))}
  return questions.slice(0,10);
};

function rpgV6EnemyPlan(node,replay=false){
  const fullDeck=rpgQuestionsForNode(node,replay),split=rpgV6StageSplit(node),questions=fullDeck.slice(split.start,split.start+split.count),specs=[
    ['e1','agile',430],['e2','ranged',690],['e3','guardian',950],['e4','agile',1210],['e5','berserker',1470],
    ['e6','ranged',1740],['e7','guardian',2010],['e8','healer',2280],['e9','large',2550],['e10','agile',2820],
    ['e11','ranged',3090],['e12','berserker',3350],['e13','guardian',3590],['e14','large',3810],['boss','boss',4050]
  ];
  const nonBoss=rpgShuffle(specs.slice(0,-1).map(x=>x[0]),`v6-souls-${node.layoutSeed}`),assign=[...nonBoss.slice(0,Math.max(0,questions.length-1)),'boss'],questionByEnemy=new Map(assign.map((id,i)=>[id,questions[i]?.id||''])),scale=rpgLevelScale(node.difficulty);
  return specs.map(([id,kind,x],i)=>{const def=RPG_MONSTERS[kind],beginner=node.id<=3?(kind==='boss'?.76:.84):1,maxHp=Math.max(6,Math.round(def.hp*scale.hp*beginner));return{id,kind,tier:def.tier,x,y:kind==='ranged'&&i%2?310:435,maxHp,hp:maxHp,attack:Math.max(0,Math.round(def.attack*scale.attack*(node.id<=3?.68:1))),defense:def.defense,skill:def.skill,hasSoul:questionByEnemy.has(id),questionId:questionByEnemy.get(id)||'',alive:true,soulResolved:false,phase:1,healEnergy:0,killSerial:0}});
}
rpgEnemyPlan=rpgV6EnemyPlan;

function rpgV6FreshRun(node,replay=false){return{version:RPG_VERSION,planVersion:6,nodeId:node.id,mapId:node.mapId,seed:rpgHash(`${node.layoutSeed}-${Date.now()}-${Math.random()}`),replay,status:'ready',startedAt:null,playerX:120,playerY:null,checkpoint:{id:'cp0',x:120,hp:ensureRpgState().player.hp||rpgComputedStats().maxHp,enemySnapshot:[],groundLootSnapshot:[],earnedCoins:0,earnedXp:0},checkpoints:['cp0'],enemies:rpgV6EnemyPlan(node,replay),openedBlocks:[],openedRooms:[],collected:[],earnedCoins:0,earnedXp:0,loot:[],groundLoot:[],targetSouls:rpgV6SoulTarget(node),soulsAnswered:[],wrongSouls:[],attempts:{},stars:0}}
rpgFreshRun=rpgV6FreshRun;
rpgEnsureRun=function(node,replay=false){
  const r=ensureRpgState();if(!r.run||r.run.nodeId!==node.id||['completed','failed'].includes(r.run.status)){r.run=rpgV6FreshRun(node,replay);return r.run}
  if(r.run.planVersion!==6){const old=r.run,fresh=rpgV6FreshRun(node,replay);for(const key of ['playerX','playerY','openedBlocks','openedRooms','collected','checkpoints','checkpoint'])if(old[key]!==undefined)fresh[key]=old[key];r.run=fresh}
  r.run.groundLoot=Array.isArray(r.run.groundLoot)?r.run.groundLoot:[];r.run.targetSouls=rpgV6SoulTarget(node);return r.run;
};

function rpgV6ActiveNode(){const r=ensureRpgState();rpgEnsureNodes(r.route.unlocked);return rpgNode(r.route.unlocked)}
gameStatusCard=function(){const r=ensureRpgState(),node=rpgUnlockToday(),map=rpgMap(node),stats=rpgComputedStats(),unlocked=rpgGameUnlocked()||node.firstClear;return`<section class="game-home-card rpg-home-card ${unlocked?'is-unlocked':'is-locked'}"><div class="rpg-home-poster map-${map.id}"><span>${rpgV5Stage(node)}</span></div><div><span class="game-kicker">${unlocked?'今日展厅已开放':'完成每日10题三轮训练后开放'}</span><h3>${rpgV5Stage(node)} · ${escapeHtml(map.name)}</h3><p>本关对应今日10个知识点。实体战斗后会随机出现灵魂题；旧关可以反复刷装备和复习错题。</p><div class="game-home-stats"><span>战力 ${stats.power}</span><span>推荐 ${node.recommendedPower}</span><span>等级 ${r.player.level}</span><span>金币 ${r.player.coins}</span></div><button class="primary-btn" onclick="rpgStartNode(${node.id},${node.firstClear})" ${unlocked?'':'disabled'}>进入 ${rpgV5Stage(node)} →</button><button class="text-btn" onclick="showView('rpgRoute')">查看88关路线</button></div></section>`};

rpgStartNode=function(id,replay=false){const r=ensureRpgState(),node=rpgNode(id),test=isRpgTest();if(node.id<1||node.id>88||!test&&node.id>r.route.unlocked){notify('该关卡尚未解锁');return}if(!test&&!node.firstClear&&node.id===r.route.unlocked&&!rpgGameUnlocked()){notify('先完成今天10题的三轮练习');return}r.route.current=node.id;rpgEnsureRun(node,Boolean(replay||node.firstClear));state.view='rpgGame';rpgPersist();render()};
enterDailyGame=function(){rpgUnlockToday();const node=rpgV6ActiveNode();rpgStartNode(node.id,node.firstClear)};

rpgItemCard=function(item,index){const rarity=rpgRarity(item),r=ensureRpgState(),stats=rpgComputedStats(),equipped=Object.values(r.equipment).flat().includes(item.id),current=item.slot==='weapon'?rpgItemById(r.equipment.weapons[r.equipment.activeWeapon]):rpgItemById(r.equipment[item.slot]),delta=Math.round((item.mainStat-(current?.mainStat||0))*10)/10,pieces=stats.setCounts[item.setId]||0,route=Object.entries(RPG_SET_ROWS).find(([,row])=>row===item.visual?.row)?.[0]||item.baseId,skill=pieces>=5&&item.rarityRank>=3?rpgSetInfo(item.rarity,route).hiddenSkill:'';return`<article class="gear-card ${equipped?'equipped':''}" style="--rarity:${rarity.color}"><div class="gear-card-top">${rpgV6IconMarkup(item,'gear-card-icon')}<header><span>${rarity.name}</span><b>${escapeHtml(item.name)}${item.upgrade?` ＋${item.upgrade}`:''}${item.locked?' · 已锁定':''}</b><p>${item.slot==='weapon'?RPG_WEAPONS[item.baseId]?.name:RPG_ARMOR[item.slot]} · Lv.${item.itemLevel} · 主属性 ${item.mainStat}</p></header></div>${!equipped?`<p class="gear-compare">相比当前 ${delta>=0?'+':''}${delta}</p>`:''}<ul>${(item.affixes||[]).map(a=>`<li class="${a.positive?'positive':'negative'}">${a.label} ${a.value>0?'+':''}${a.value}%${a.fixed?' · 固定':''}</li>`).join('')}${item.setId?`<li class="set-bonus">${escapeHtml(item.setName||item.setId)} · ${pieces}/5</li>`:''}${skill?`<li class="legendary">隐藏技能：${escapeHtml(skill)}</li>`:''}${item.legendaryEffect?`<li class="legendary">${escapeHtml(item.legendaryEffect)}</li>`:''}<li class="negative">代价：${escapeHtml(item.drawback||'无')}</li></ul><footer>${item.slot==='weapon'?`<button onclick="rpgEquipAndRender('${item.id}',${index%3})">装备到${index%3+1}</button>`:`<button onclick="rpgEquipAndRender('${item.id}')">装备</button>`}<button onclick="rpgUpgradeAndRender('${item.id}')">强化</button><button onclick="rpgLockAndRender('${item.id}')">${item.locked?'解锁':'锁定'}</button><button onclick="rpgDismantleAndRender('${item.id}')" ${item.locked||equipped?'disabled':''}>分解</button></footer></article>`};

function rpgV6TestEquip(baseId='staff'){if(!isRpgTest()||!RPG_WEAPONS[baseId])return;const r=ensureRpgState(),set=rpgSetInfo('fine',baseId),parts=['weapon','helmet','chest','bracer','boots'];for(const [col,slot] of parts.entries()){const id=`test-${baseId}-${slot}`;let item=r.inventory.find(x=>x.id===id);if(!item){item={...rpgStarterSword(),id,baseId:slot==='weapon'?baseId:slot,slot,name:`测试${set.name}·${slot==='weapon'?RPG_WEAPONS[baseId].name:RPG_ARMOR[slot]}`,rarity:'fine',rarityRank:3,setId:set.id,setName:set.name,mainStat:slot==='weapon'?18:10,visual:{atlas:'fine',row:set.row,col},locked:true};r.inventory.push(item)}if(slot==='weapon')r.equipment.weapons[0]=id;else r.equipment[slot]=id}r.equipment.activeWeapon=0;const stats=rpgComputedStats();r.player.mana=stats.maxMana;r.player.hp=Math.min(r.player.hp,stats.maxHp);rpgScene?.refreshWeapon();rpgRenderHud();rpgPersist()}
function rpgV6TestRefill(){if(!isRpgTest())return;const r=ensureRpgState(),stats=rpgComputedStats();r.player.hp=stats.maxHp;r.player.mana=stats.maxMana;rpgRenderHud()}
function rpgV6TestSoul(){if(!isRpgTest()||!rpgScene||rpgScene.soulBattle)return;const enemy=rpgScene.enemies.find(x=>x.active&&x.dataRef.hasSoul);if(!enemy)return;enemy.dataRef.hp=0;rpgScene.updateEnemyBar(enemy);rpgScene.physicalDefeat(enemy)}
function rpgV6TestPortal(){if(!isRpgTest()||!rpgScene)return;for(const ref of rpgScene.run.enemies){if(ref.hasSoul&&!rpgScene.run.soulsAnswered.includes(ref.questionId))rpgScene.run.soulsAnswered.push(ref.questionId);ref.soulResolved=true;ref.alive=false}rpgScene.updatePortalState();rpgScene.player.setPosition(rpgScene.portal.x-170,420);rpgScene.updatePortalPrompt();rpgRenderHud()}
function rpgV6TestCheckpoint(){if(!isRpgTest()||!rpgScene)return;const cp=rpgScene.checkpoints?.getChildren?.()[1];if(!cp)return;rpgScene.player.setPosition(cp.x,420);rpgScene.settlePlayerOnSurface(cp.x);rpgScene.activateCheckpoint(cp);notify('测试记录点已激活')}
function rpgV6TestDrop(){if(!isRpgTest()||!rpgScene)return;const r=ensureRpgState(),ref={id:`test-${Date.now()}`,x:rpgScene.player.x+105,y:rpgScene.player.y,tier:'medium'},item=rpgGenerateGear({tier:'medium',level:rpgScene.node.id,seed:`test-drop-${rpgScene.node.id}-${Date.now()}`,rarityId:'common'});rpgScene.spawnLootDrops(ref,{coins:18,xp:24,items:[item],consumables:['mana']});notify('已生成金币、装备与法力道具')}
function rpgV6TestCollect(){if(!isRpgTest()||!rpgScene)return;for(const pickup of [...(rpgScene.pickups?.getChildren?.()||[])])rpgScene.collectPickup(pickup)}

function rpgV6AssignQuickItem(id,index){const r=ensureRpgState();if(!RPG_CONSUMABLES[id]||index<0||index>2)return;r.equipment.quickItems[index]=id;rpgPersist();render()}
rpgInventoryView=function(){
  const r=ensureRpgState(),stats=rpgComputedStats(),items=[...r.inventory].sort((a,b)=>b.rarityRank-a.rarityRank||b.itemLevel-a.itemLevel),armorSlots=['helmet','chest','bracer','boots'];
  const itemBar=Object.entries(RPG_CONSUMABLES).map(([id,def])=>`<article class="consumable-card">${rpgV6IconMarkup(id,'loadout-icon')}<div><b>${escapeHtml(def.name)}</b><span>${escapeHtml(def.description)}</span><small>持有 ${r.consumables[id]||0}</small></div><footer>${[0,1,2].map(i=>`<button class="${r.equipment.quickItems[i]===id?'active':''}" onclick="rpgV6AssignQuickItem('${id}',${i})">放入 ${i+4}</button>`).join('')}</footer></article>`).join('');
  return shell('装备工坊','MUSEUM LOADOUT · IMAGE CATALOG',`<div class="course-tabs"><button onclick="showView('course')">学习章节</button><button onclick="showView('rpgRoute')">冒险路线</button><button class="active">装备工坊</button></div><div class="workshop-hero"><div><span>战力</span><strong>${stats.power}</strong><p>生命 ${stats.maxHp} · 法力 ${stats.maxMana}（每秒恢复 ${stats.manaRegen}）· 攻击 ${stats.attack} · 防御 ${stats.defense} · 暴击 ${Math.round(stats.crit*100)}%</p></div><div class="currency"><b>${rpgV6IconMarkup('coins','currency-icon')} ${r.player.coins}</b><b>粉尘 ${r.player.dust}</b><b>背包 ${r.inventory.length}/120</b></div></div><section class="loadout museum-loadout"><h3>当前携带</h3><div class="armor-slots">${armorSlots.map(slot=>{const item=rpgItemById(r.equipment[slot]);return`<div class="image-slot" style="--rarity:${item?rpgRarity(item).color:'#405767'}">${rpgV6IconMarkup(item||slot,'loadout-icon')}<span>${RPG_ARMOR[slot]}</span><b>${item?escapeHtml(item.name):'未装备'}</b></div>`}).join('')}</div><div class="weapon-slots">${r.equipment.weapons.map((id,i)=>{const item=rpgItemById(id);return`<button class="weapon-slot image-slot ${i===r.equipment.activeWeapon?'active':''}" onclick="rpgActivateWeapon(${i})" style="--rarity:${item?rpgRarity(item).color:'#405767'}"><span class="slot-key">${i+1}</span>${rpgV6IconMarkup(item,'loadout-icon')}<b>${item?escapeHtml(item.name):'空武器栏'}</b></button>`}).join('')}</div></section><section class="consumable-workshop"><h3>快捷道具</h3><p>每种道具都有独立模组。选择放入4、5、6号快捷栏。</p><div>${itemBar}</div></section><div class="gear-grid">${items.map(rpgItemCard).join('')}</div>`)
};

rpgGameView=function(){const r=ensureRpgState(),node=rpgCurrentNode(),run=rpgEnsureRun(node,node.firstClear),map=rpgMap(node),stats=rpgComputedStats(),test=isRpgTest(),target=run.targetSouls||rpgV6SoulTarget(node);r.player.mana=Math.min(r.player.mana,stats.maxMana);return`<div class="rpg-shell map-${map.id}"><div id="rpgCanvas"></div><div class="rpg-hud"><span class="test-badge">${test?'独立测试 · 不保存':''}</span><span class="stage-chip">${rpgV5Stage(node)}</span><div class="hud-bars"><div class="hud-health"><i id="rpgPlayerHp" style="width:${Math.max(0,r.player.hp/stats.maxHp*100)}%"></i><b id="rpgHpLabel">${Math.ceil(r.player.hp)}/${stats.maxHp}</b></div><div class="hud-mana"><i id="rpgPlayerMana" style="width:${Math.max(0,r.player.mana/stats.maxMana*100)}%"></i><b id="rpgManaLabel">${Math.floor(r.player.mana)}/${stats.maxMana}</b></div></div><span>Lv.${r.player.level}</span><span>${rpgV6IconMarkup('coins','hud-icon')} <b id="rpgCoins">${r.player.coins}</b></span><span>灵魂 <b id="rpgSoulCount">${run.soulsAnswered.length}/${target}</b></span><button onclick="rpgExitGame()">撤离</button></div><div class="weapon-switch">${r.equipment.weapons.map((id,i)=>{const item=rpgItemById(id);return`<button data-weapon="${i}" onclick="rpgSwitchWeapon(${i})" class="${i===r.equipment.activeWeapon?'active':''}" title="${item?escapeHtml(item.name):'空武器栏'}"><span>${i+1}</span>${rpgV6IconMarkup(item,'hud-loadout-icon')}<b>${item?escapeHtml(item.name):'空'}</b></button>`}).join('')}</div><div class="quick-items">${r.equipment.quickItems.map((id,i)=>`<button onclick="rpgUseItem(${i})" title="${escapeHtml(RPG_CONSUMABLES[id]?.name||'道具')}"><span>${i+4}</span>${rpgV6IconMarkup(id,'hud-loadout-icon')}<b>${r.consumables[id]||0}</b></button>`).join('')}</div>${test?`<div class="rpg-test-tools"><button onclick="rpgV6TestEquip('staff')">法杖套装</button><button onclick="rpgV6TestRefill()">补满状态</button><button onclick="rpgV6TestSoul()">召唤灵魂</button><button onclick="rpgV6TestCheckpoint()">测试记录点</button><button onclick="rpgV6TestDrop()">生成掉落</button><button onclick="rpgV6TestCollect()">拾取掉落</button><button onclick="rpgV6TestPortal()">开启传送门</button></div>`:''}<div class="rpg-controls"><div><button data-rpg="left">←</button><button data-rpg="right">→</button></div><div><button data-rpg="jump">跳</button><button data-rpg="dodge">闪</button><button data-rpg="attack">攻</button></div></div><div class="rotate-note"><div><strong>请把手机横过来</strong><p>横屏后才能完整操作。</p></div></div><div class="rpg-start" id="rpgStart"><div><small>${rpgV5Stage(node)} · 推荐战力 ${node.recommendedPower}</small><h2>${escapeHtml(map.name)}</h2><p>本展厅有${target}只题目灵魂，其余怪物用于动作战斗。装备、金币和道具会掉在地面，靠近后自动拾取。</p><button onclick="rpgLaunch()">进入 ${rpgV5Stage(node)}</button></div></div><div id="rpgModal"></div></div>`};

rpgRouteView=function(){const r=ensureRpgState();rpgEnsureNodes(r.route.unlocked);const stats=rpgComputedStats(),test=isRpgTest(),nodes=r.route.nodes.slice(0,Math.min(88,r.route.unlocked+5));return shell('艺术博物馆冒险路线','MUSEUM EXPEDITION · 88 STAGES',`<div class="course-tabs"><button onclick="showView('course')">学习章节</button><button class="active">冒险路线</button><button onclick="showView('rpgInventory')">装备工坊</button></div><div class="route-summary"><div><span>角色等级</span><strong>${r.player.level}</strong></div><div><span>当前战力</span><strong>${stats.power}</strong></div><div><span>金币</span><strong>${r.player.coins}</strong></div><div><span>艺术粉尘</span><strong>${r.player.dust}</strong></div></div><div class="rpg-route">${nodes.map((n,i)=>{const map=rpgMap(n),done=n.firstClear||n.status==='completed',available=test||n.id<r.route.unlocked||n.id===r.route.unlocked&&Boolean(n.sourceDate),locked=!available&&!done;return`<article class="route-node ${locked?'locked':done?'done':'current'} map-${map.id}" style="--node-accent:${map.accent};--route-shift:${i%2?1:-1}"><button ${locked?'disabled':''} onclick="rpgStartNode(${n.id},${done})"><span class="node-medal">${locked?'◆':rpgV5Stage(n)}</span><div><small>${done?'可重复挑战':test?'独立测试可进入':available?'今日新关':'完成下一次三轮训练后开放'}</small><h3>${escapeHtml(map.name)}</h3><p>${rpgV6SoulTarget(n)}道灵魂题 · 推荐战力 ${n.recommendedPower}</p><b>${done?`${'★'.repeat(n.stars)}${'☆'.repeat(3-n.stars)}`:'进入关卡'}</b></div></button></article>`}).join('')}</div>`)};

const rpgV6BaseRenderHud=rpgRenderHud;
rpgRenderHud=function(){rpgV6BaseRenderHud();const r=ensureRpgState(),stats=rpgComputedStats(),run=r.run,soul=document.getElementById('rpgSoulCount'),mana=document.getElementById('rpgPlayerMana'),label=document.getElementById('rpgManaLabel');r.player.mana=Math.max(0,Math.min(r.player.mana,stats.maxMana));if(soul)soul.textContent=`${run?.soulsAnswered?.length||0}/${run?.targetSouls||10}`;if(mana)mana.style.width=`${r.player.mana/stats.maxMana*100}%`;if(label)label.textContent=`${Math.floor(r.player.mana)}/${stats.maxMana}`};

rpgShowResult=function(node,stars){const r=ensureRpgState(),next=node.id<88?rpgNode(node.id+1):null,canContinue=Boolean(next&&next.sourceDate===rpgToday()&&(isRpgTest()||rpgGameUnlocked()));const host=document.getElementById('rpgModal');if(host)host.innerHTML=`<section class="rpg-result"><small>${rpgV5Stage(node)} 完成并已存档</small><h2>${escapeHtml(node.mapName)}</h2><div>${'★'.repeat(stars)}${'☆'.repeat(3-stars)}</div><p>${node.id>=88?'88关冒险路线已经全部完成。':canContinue?`${rpgV5Stage(next)} 已开放，进入下一座展厅。`:'下一关将在完成下一次每日10题三轮训练后开放；本关可以随时复刷。'}</p>${canContinue?`<button onclick="rpgContinueNext(${next.id})">进入 ${rpgV5Stage(next)}</button>`:''}<button onclick="rpgExitGame()">返回冒险路线</button></section>`};

class RpgSceneV6 extends RpgSceneV5{
  preload(){super.preload();this.load.image(RPG_V6_ITEM_ATLASES.weapon,'assets/art/rpg-weapons-v2.png');this.load.image(RPG_V6_ITEM_ATLASES.gear,'assets/art/rpg-gear-consumables-v2.png');for(const [rarity,key] of Object.entries(RPG_V6_SET_ATLASES))this.load.image(key,`assets/art/rpg-set-${rarity}-v1.png`);for(const [rarity,key] of Object.entries(RPG_V6_HERO_ATLASES))this.load.image(key,`assets/art/rpg-hero-set-${rarity}-v1.png`)}
  create(){super.create();this.physics.world.setBounds(0,0,RPG_V6_WORLD_END,RPG_VIEW_H);this.cameras.main.setBounds(0,0,RPG_V6_WORLD_END,RPG_VIEW_H);this.createItemTextures();this.createLootSystem();this.createPortalPrompt();this.updatePortalState()}
  compositeHeroKey(){
    const appearance=rpgV6HeroAppearance();if(this.textures.exists(appearance.key))return appearance.key;
    const source=this.textures.get(appearance.atlas).getSourceImage(),cellW=source.width/3,cellH=source.height/5,sourceCell=document.createElement('canvas'),sourceCtx=sourceCell.getContext('2d',{willReadFrequently:true});sourceCell.width=source.width;sourceCell.height=Math.ceil(cellH);sourceCtx.drawImage(source,0,appearance.row*cellH,source.width,cellH,0,0,sourceCell.width,sourceCell.height);
    const pixels=sourceCtx.getImageData(0,0,sourceCell.width,sourceCell.height).data,bounds=[];for(let col=0;col<3;col++){let minX=sourceCell.width,maxX=-1;const left=Math.floor(col*cellW),right=Math.min(sourceCell.width,Math.ceil((col+1)*cellW)),rowMass=new Array(sourceCell.height).fill(0);for(let y=0;y<sourceCell.height;y++)for(let x=left;x<right;x++)if(pixels[(y*sourceCell.width+x)*4+3]>24){minX=Math.min(minX,x);maxX=Math.max(maxX,x);rowMass[y]++}const segments=[];let segment=null,last=-99;for(let y=0;y<rowMass.length;y++)if(rowMass[y]){if(!segment||y-last>6){segment={start:y,end:y,mass:0};segments.push(segment)}segment.end=y;segment.mass+=rowMass[y];last=y}segment=segments.sort((a,b)=>b.mass-a.mass)[0];bounds.push(segment&&maxX>=minX?{x:minX,y:segment.start,w:maxX-minX+1,h:segment.end-segment.start+1}:{x:left,y:0,w:right-left,h:sourceCell.height})}
    const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');canvas.width=1536;canvas.height=1024;ctx.imageSmoothingEnabled=false;const draw=(frame,col,yShift=0,scaleShift=1)=>{const b=bounds[col],scale=Math.min(236/b.w,226/b.h)*scaleShift,dw=b.w*scale,dh=b.h*scale,dx=(frame%6)*256+(256-dw)/2,dy=Math.floor(frame/6)*256+226-dh+yShift;ctx.drawImage(sourceCell,b.x,b.y,b.w,b.h,dx,dy,dw,dh)};for(let i=0;i<6;i++)draw(i,0,i%2?-1:0,1+(i%3)*.006);for(let i=6;i<12;i++)draw(i,1,i%2?-3:1,1);draw(12,1,-8,.98);draw(13,1,4,.98);for(let i=18;i<21;i++)draw(i,2,(i-19)*-2,.94+(.04*(i-18)));this.textures.addSpriteSheet(appearance.key,canvas,{frameWidth:256,frameHeight:256});return appearance.key;
  }
  makeLayout(){super.makeLayout();if(this.node.mapId==='cathedral')for(const child of [...this.children.list])if(child.type==='Triangle'&&child.depth===-9)child.destroy()}
  createItemTextures(){if(this.textures.exists('rpg-item-sword'))return;for(const [key,meta] of Object.entries(RPG_V6_ICON_META)){const source=this.textures.get(RPG_V6_ITEM_ATLASES[meta.atlas]).getSourceImage(),cellW=source.width/meta.cols,cellH=source.height/meta.rows,col=meta.index%meta.cols,row=Math.floor(meta.index/meta.cols),texture=this.textures.createCanvas(`rpg-item-${key}`,128,128),ctx=texture.getContext();ctx.clearRect(0,0,128,128);ctx.drawImage(source,col*cellW,row*cellH,cellW,cellH,0,0,128,128);texture.refresh()}for(const [rarity,atlasKey] of Object.entries(RPG_V6_SET_ATLASES)){const source=this.textures.get(atlasKey).getSourceImage(),cellW=source.width/5,cellH=source.height/5;for(let row=0;row<5;row++)for(let col=0;col<5;col++){const texture=this.textures.createCanvas(`rpg-set-${rarity}-${row}-${col}`,128,128),ctx=texture.getContext();ctx.clearRect(0,0,128,128);ctx.drawImage(source,col*cellW,row*cellH,cellW,cellH,0,0,128,128);texture.refresh()}}}
  createLootSystem(){this.pickups=this.physics.add.group({allowGravity:true});for(const entry of this.run.groundLoot||[])if(!entry.collected)this.spawnPickupSprite(entry);this.physics.add.collider(this.pickups,this.solids);this.physics.add.overlap(this.player,this.pickups,(player,pickup)=>{if(Phaser.Math.Distance.Between(player.x,player.y,pickup.x,pickup.y)<82)this.collectPickup(pickup)})}
  activateCheckpoint(cp){const wasActive=Boolean(cp.flag?.active);super.activateCheckpoint(cp);if(wasActive||this.run.checkpoint?.id!==cp.cpId)return;this.run.checkpoint.groundLootSnapshot=JSON.parse(JSON.stringify(this.run.groundLoot||[]));this.run.checkpoint.earnedCoins=this.run.earnedCoins||0;this.run.checkpoint.earnedXp=this.run.earnedXp||0;rpgPersist()}
  pickupIcon(entry){if(entry.kind==='coins')return'coins';if(entry.kind==='consumable')return entry.consumable;return entry.item?.baseId||entry.item?.slot||'coins'}
  spawnPickupSprite(entry){const key=this.pickupIcon(entry),visual=entry.item?.visual,texture=visual&&RPG_V6_SET_ATLASES[visual.atlas]?`rpg-set-${visual.atlas}-${visual.row}-${visual.col}`:`rpg-item-${RPG_V6_ICON_META[key]?key:'coins'}`,sprite=this.physics.add.sprite(entry.x,entry.y,texture).setDisplaySize(entry.kind==='gear'?54:46,entry.kind==='gear'?54:46).setDepth(26);sprite.body.setSize(82,82).setBounce(.28).setCollideWorldBounds(true);sprite.setVelocity(Phaser.Math.Between(-75,75),Phaser.Math.Between(-185,-125));sprite.pickupData=entry;const rarity=entry.item?rpgRarity(entry.item):null,aura=this.add.ellipse(entry.x,entry.y+18,entry.kind==='gear'?58:46,15,rarity?Phaser.Display.Color.HexStringToColor(rarity.color).color:0x55dfff,.2).setStrokeStyle(2,rarity?Phaser.Display.Color.HexStringToColor(rarity.color):0x8eeeff,.85).setDepth(24);sprite.pickupAura=aura;this.pickups.add(sprite);this.tweens.add({targets:sprite,scaleX:{from:sprite.scaleX*.94,to:sprite.scaleX*1.06},scaleY:{from:sprite.scaleY*1.06,to:sprite.scaleY*.94},duration:620,yoyo:true,repeat:-1});return sprite}
  spawnLootDrops(ref,loot){const entries=[],baseX=Math.max(60,Math.min(RPG_V6_WORLD_END-160,ref.x)),add=(data,offset)=>{const entry={id:`drop-${ref.id}-${this.run.groundLoot.length+entries.length}-${Date.now()}`,x:baseX+offset,y:Math.min(390,ref.y-35),collected:false,...data};entries.push(entry);this.run.groundLoot.push(entry);this.spawnPickupSprite(entry)};if(loot.coins||loot.xp)add({kind:'coins',coins:loot.coins||0,xp:loot.xp||0},-30);for(const [i,item] of (loot.items||[]).entries())add({kind:'gear',item},10+i*38);for(const [i,consumable] of (loot.consumables||[]).entries())add({kind:'consumable',consumable},25+i*34);this.floatText(baseX,Math.min(340,ref.y-95),`掉落 ${entries.length} 件战利品`,0x68eaff);rpgPersist()}
  collectPickup(sprite){if(!sprite?.active||sprite.collecting)return;sprite.collecting=true;const entry=sprite.pickupData;this.tweens.killTweensOf(sprite);this.tweens.add({targets:[sprite,sprite.pickupAura],x:this.player.x,y:this.player.y-20,scale:.2,alpha:0,duration:170,onComplete:()=>{const loot={coins:entry.coins||0,xp:entry.xp||0,items:entry.item?[entry.item]:[],consumables:entry.consumable?[entry.consumable]:[]};entry.collected=true;rpgAddRunReward(loot);sprite.pickupAura?.destroy();sprite.destroy();const label=entry.kind==='coins'?`+${entry.coins} 金币`:entry.kind==='gear'?entry.item.name:RPG_CONSUMABLES[entry.consumable]?.name||'道具';this.floatText(this.player.x,this.player.y-70,label,entry.item?Phaser.Display.Color.HexStringToColor(rpgRarity(entry.item).color).color:0xffdc68);rpgV5Sound('reward');rpgRenderHud();rpgPersist()}})}
  createPortal(){const x=RPG_V6_WORLD_END-150,halo=this.add.ellipse(x,375,150,228,0x13dfff,.2).setStrokeStyle(7,0x8ff8ff,1).setDepth(10),outer=this.add.ellipse(x,375,120,198,0x05c8ff,.5).setStrokeStyle(11,0x58efff,1).setDepth(12),inner=this.add.ellipse(x,375,76,158,0x0579ff,1).setStrokeStyle(5,0xe8ffff,1).setDepth(11),rune=this.add.star(x,375,8,21,34,0xeaffff,1).setDepth(13),zone=this.add.zone(x,390,160,205),wall=this.add.zone(x+94,240,32,480);this.physics.add.existing(zone,true);this.physics.add.existing(wall,true);this.solids.add(wall);this.physics.add.collider(this.player,wall);this.portal={x,halo,outer,inner,rune,zone,active:false,transitioning:false,lastTouch:0};this.physics.add.overlap(this.projectiles,zone,p=>{p.destroy();this.tryPortalStrike('projectile')});this.physics.add.overlap(this.player,zone,()=>{this.portal.lastTouch=this.time.now});this.tweens.add({targets:rune,angle:360,duration:3600,repeat:-1});this.tweens.add({targets:halo,scale:{from:.9,to:1.13},alpha:{from:.55,to:1},duration:720,yoyo:true,repeat:-1});this.updatePortalState()}
  updatePortalState(){if(!this.portal)return;const boss=this.run.enemies.find(e=>e.id==='boss'),active=Boolean(boss&&!boss.alive&&boss.soulResolved);if(active&&!this.portal.active){this.portal.active=true;this.portal.halo.setFillStyle(0x16e8ff,.28).setStrokeStyle(6,0xbdfcff,1);this.portal.outer.setFillStyle(0x16cfff,.55).setStrokeStyle(10,0x7cffff,1);this.portal.inner.setFillStyle(0x058fff,1);this.portal.rune.setFillStyle(0xffffff,1);this.tweens.add({targets:[this.portal.outer,this.portal.inner],scale:{from:.96,to:1.08},alpha:{from:.72,to:1},duration:620,yoyo:true,repeat:-1});this.floatText(this.portal.x,255,'传送门已开启 · 靠近并攻击',0x9ffcff);rpgV5Sound('portal')}}
  tryPortalStrike(source='melee'){if(!this.portal?.active||this.portal.transitioning)return false;const near=Math.abs(this.player.x-this.portal.x)<=285||this.time.now-(this.portal.lastTouch||0)<250;if(source!=='projectile'&&!near)return false;this.portal.transitioning=true;rpgV5Sound('portal');this.cameras.main.flash(160,80,235,255);this.cameras.main.fadeOut(430,8,95,170);this.time.delayedCall(440,()=>this.completeV5Run());return true}
  createPortalPrompt(){const host=document.querySelector('.rpg-shell');if(!host)return;const prompt=document.createElement('div');prompt.id='rpgPortalPrompt';prompt.className='portal-prompt';prompt.setAttribute('aria-live','polite');host.appendChild(prompt);this.portalPrompt=prompt}
  updatePortalPrompt(){const host=this.portalPrompt;if(!host||!this.portal||!this.player)return;const near=Math.abs(this.player.x-this.portal.x)<330;if(!near){host.classList.remove('is-visible');host.textContent='';return}if(!this.portal.active){host.classList.add('is-visible','is-locked');host.textContent='击败本关 Boss 后开启传送门';return}host.classList.add('is-visible');host.classList.remove('is-locked');host.textContent='靠近传送门 · 按 E / F / J / 攻击键进入下一关'}
  completeV5Run(){const r=ensureRpgState(),node=this.node,elapsed=(Date.now()-new Date(this.run.startedAt).getTime())/1000,target=this.run.targetSouls||rpgV6SoulTarget(node);this.run.status='completed';this.run.stars=1+(r.player.hp/rpgComputedStats().maxHp>=.5?1:0)+(this.run.soulsAnswered.length>=target?1:0);node.firstClear=true;node.status='completed';node.stars=Math.max(node.stars,this.run.stars);node.bestTime=node.bestTime?Math.min(node.bestTime,elapsed):elapsed;if(node.id===r.route.unlocked&&node.id<88){r.route.unlocked++;rpgEnsureNodes(r.route.unlocked);const next=rpgNode(r.route.unlocked);next.status='locked';if(isRpgTest()){next.sourceDate=rpgToday();next.status='available'}}this.physics.pause();this.scene.pause();const stars=this.run.stars;r.run=null;rpgPersist();rpgShowResult(node,stars)}
  finishEnemy(ref,soul){ref.alive=false;ref.soulResolved=soul||ref.soulResolved;const loot=rpgRollMonsterLoot(ref,this.run);this.spawnLootDrops(ref,loot);if(ref.id==='boss')this.updatePortalState();rpgRenderHud();rpgPersist();this.time.delayedCall(40,()=>this.settlePlayerOnSurface())}
  syncShieldEffect(){const active=ensureRpgState().player.shield;if(active&&!this.shieldFx){const rear=this.add.ellipse(0,7,124,34,0x22dfff,.09).setStrokeStyle(4,0x65efff,.95),front=this.add.ellipse(0,9,104,24,0x4be8ff,.04).setStrokeStyle(2,0xc8ffff,.8),dotA=this.add.circle(0,0,5,0xe9ffff,1).setStrokeStyle(2,0x29dfff),dotB=this.add.circle(0,0,4,0x79f7ff,1).setStrokeStyle(2,0xffffff);this.shieldFx=this.add.container(this.player.x,this.player.y+10,[rear,front,dotA,dotB]).setDepth(28);this.shieldRing=rear;this.shieldDots=[dotA,dotB];this.tweens.add({targets:[rear,front],alpha:{from:.45,to:1},scaleX:{from:.93,to:1.08},scaleY:{from:.88,to:1.12},duration:760,yoyo:true,repeat:-1})}if(!active&&this.shieldFx){this.shieldFx.destroy(true);this.shieldFx=null;this.shieldDots=null;this.shieldRing=null}}
  breakShield(){const wave=this.add.ellipse(this.player.x,this.player.y+8,116,36,0x40e8ff,.15).setStrokeStyle(6,0xe9ffff).setDepth(30);this.tweens.add({targets:wave,scaleX:2.2,scaleY:1.7,alpha:0,duration:360,onComplete:()=>wave.destroy()});for(let i=0;i<12;i++){const a=Math.PI*2*i/12,p=this.add.circle(this.player.x,this.player.y+8,3,0x9af9ff,1).setDepth(31);this.tweens.add({targets:p,x:p.x+Math.cos(a)*90,y:p.y+Math.sin(a)*34,alpha:0,duration:330,onComplete:()=>p.destroy()})}rpgV5Sound('shield');this.time.delayedCall(40,()=>this.syncShieldEffect())}
  failToCheckpoint(){const checkpoint=this.run.checkpoint||{},snapshot=JSON.parse(JSON.stringify(checkpoint.groundLootSnapshot||[]));for(const pickup of this.pickups?.getChildren?.()||[]){pickup.pickupAura?.destroy();pickup.destroy()}this.pickups?.clear?.(true,true);this.run.groundLoot=snapshot;super.failToCheckpoint();this.time.delayedCall(60,()=>{for(const entry of this.run.groundLoot||[])if(!entry.collected)this.spawnPickupSprite(entry)})}
  update(time,delta){if(!this.keys?.E)this.keys.E=this.input.keyboard.addKey('E');if(Phaser.Input.Keyboard.JustDown(this.keys.E)){if(this.tryPortalStrike('melee'))return;rpgInput.attack=true}super.update(time,delta);if(!this.player?.body||this.soulBattle)return;const r=ensureRpgState(),stats=rpgComputedStats();this.lastManaTick=this.lastManaTick||time;if(time-this.lastManaTick>=200){const elapsed=(time-this.lastManaTick)/1000;r.player.mana=Math.min(stats.maxMana,r.player.mana+stats.manaRegen*elapsed);this.lastManaTick=time;rpgRenderHud()}this.updatePortalPrompt();if(this.shieldFx&&this.shieldDots){this.shieldFx.setPosition(this.player.x,this.player.y+9);const a=time*.0055;this.shieldDots[0].setPosition(Math.cos(a)*61,Math.sin(a)*13);this.shieldDots[1].setPosition(Math.cos(a+Math.PI)*61,Math.sin(a+Math.PI)*13)}for(const pickup of this.pickups?.getChildren?.()||[]){pickup.pickupAura?.setPosition(pickup.x,pickup.y+18);if(!pickup.collecting&&Phaser.Math.Distance.Between(this.player.x,this.player.y,pickup.x,pickup.y)<86)this.collectPickup(pickup)}}
}

rpgLaunch=function(){if(isRpgTest()&&!rpgTestBackup)rpgTestBackup=JSON.stringify(state.rpg);const node=rpgCurrentNode();rpgEnsureRun(node,node.firstClear);document.getElementById('rpgStart')?.remove();rpgDestroy();const config={type:Phaser.AUTO,parent:'rpgCanvas',width:RPG_VIEW_W,height:RPG_VIEW_H,backgroundColor:'#091522',pixelArt:true,physics:{default:'arcade',arcade:{gravity:{y:920},debug:false}},scene:[RpgSceneV6]};rpgInstance=new Phaser.Game(config)};

window.__RPG_V6__={version:3,target:()=>rpgScene?.run?.targetSouls||rpgV6SoulTarget(rpgCurrentNode()),drops:()=>rpgScene?.run?.groundLoot||[],heroAppearance:()=>rpgV6HeroAppearance(),heroTexture:()=>rpgScene?.player?.texture?.key||'',mana:()=>({value:ensureRpgState().player.mana,max:rpgComputedStats().maxMana}),portalStrike:(source='melee')=>rpgScene?.tryPortalStrike(source),collectAll:()=>{for(const p of [...(rpgScene?.pickups?.getChildren?.()||[])])rpgScene.collectPickup(p)}};
if(isRpgTest()){state.view='rpgGame';render()}
