/* RPG第五版：完整武器角色模组、单一换装纹理、蓝旗记录点与分段传送门。 */
const RPG_V5_WORLD_END=4380;
const RPG_V5_HERO_TEXTURES={sword:'rpg-hero-v6-sword',greatsword:'rpg-hero-v6-greatsword',dual:'rpg-hero-v6-dual',bow:'rpg-hero-v6-bow'};

function rpgV5EnemyPlan(node,replay=false){
  const questions=rpgQuestionsForNode(node,replay),specs=[
    ['e1','agile',520],['e2','agile',810],['e3','guardian',1100],['e4',node.id>1?'ranged':'agile',1390],
    ['e5','agile',1680],['e6','berserker',1980],['e7','guardian',2280],['e8',node.id>2?'ranged':'agile',2580],
    ['e9','agile',2880],['e10','large',3210],['e11',node.id>3?'healer':'guardian',3520],['boss','boss',4010]
  ];
  const assign=[...rpgShuffle(specs.slice(0,-1).map(x=>x[0]),`v5-souls-${node.layoutSeed}`).slice(0,Math.min(9,questions.length-1)),'boss'];
  const scale=rpgLevelScale(node.difficulty);
  return specs.map(([id,kind,x],i)=>{const def=RPG_MONSTERS[kind],hasSoul=assign.includes(id),questionIndex=assign.indexOf(id),beginner=node.id<=3?(kind==='boss'?0.82:0.88):1,maxHp=Math.max(6,Math.round(def.hp*scale.hp*beginner));return{id,kind,tier:def.tier,x,y:kind==='ranged'&&i%2?310:435,maxHp,hp:maxHp,attack:Math.max(0,Math.round(def.attack*scale.attack*(node.id<=3?0.75:1))),defense:def.defense,skill:def.skill,hasSoul,questionId:questionIndex>=0?questions[questionIndex]?.id:'',alive:true,soulResolved:false,phase:1,healEnergy:0,killSerial:0}})
}
rpgEnemyPlan=rpgV5EnemyPlan;
function rpgV5FreshRun(node,replay=false){return{version:RPG_VERSION,planVersion:5,nodeId:node.id,mapId:node.mapId,seed:rpgHash(`${node.layoutSeed}-${Date.now()}-${Math.random()}`),replay,status:'ready',startedAt:null,playerX:120,playerY:null,checkpoint:{id:'cp0',x:120,hp:ensureRpgState().player.hp||rpgComputedStats().maxHp,enemySnapshot:[]},checkpoints:['cp0'],enemies:rpgV5EnemyPlan(node,replay),openedBlocks:[],openedRooms:[],collected:[],earnedCoins:0,earnedXp:0,loot:[],soulsAnswered:[],wrongSouls:[],attempts:{},stars:0}}
rpgFreshRun=rpgV5FreshRun;
rpgEnsureRun=function(node,replay=false){const r=ensureRpgState();if(!r.run||r.run.planVersion!==5||r.run.nodeId!==node.id||['completed','failed'].includes(r.run.status))r.run=rpgV5FreshRun(node,replay);return r.run}

function rpgV5Audio(){
  try{const Ctx=window.AudioContext||window.webkitAudioContext;if(!Ctx)return null;const ctx=rpgV5Audio.ctx||(rpgV5Audio.ctx=new Ctx());if(ctx.state==='suspended')ctx.resume();return ctx}catch(e){return null}
}
function rpgV5Tone(from,to=.5,duration=.09,type='triangle',gain=.055){
  const ctx=rpgV5Audio();if(!ctx)return;const o=ctx.createOscillator(),g=ctx.createGain(),now=ctx.currentTime;o.type=type;o.frequency.setValueAtTime(from,now);o.frequency.exponentialRampToValueAtTime(Math.max(30,from*to),now+duration);g.gain.setValueAtTime(gain,now);g.gain.exponentialRampToValueAtTime(.001,now+duration);o.connect(g).connect(ctx.destination);o.start(now);o.stop(now+duration)
}
function rpgV5Noise(duration=.08,gain=.04,highpass=700){
  const ctx=rpgV5Audio();if(!ctx)return;const frames=Math.max(1,Math.floor(ctx.sampleRate*duration)),buffer=ctx.createBuffer(1,frames,ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<frames;i++)data[i]=(Math.random()*2-1)*(1-i/frames);const src=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),g=ctx.createGain();src.buffer=buffer;filter.type='highpass';filter.frequency.value=highpass;g.gain.value=gain;src.connect(filter).connect(g).connect(ctx.destination);src.start()
}
function rpgV5Sound(name){
  if(name==='swing'){rpgV5Noise(.11,.035,900);rpgV5Tone(760,.32,.1,'sine',.035)}
  else if(name==='heavy'){rpgV5Noise(.18,.06,260);rpgV5Tone(210,.42,.17,'sawtooth',.055)}
  else if(name==='arrow'){rpgV5Noise(.07,.025,1500);rpgV5Tone(1050,.58,.07,'triangle',.025)}
  else if(name==='hit'){rpgV5Noise(.09,.055,320);rpgV5Tone(150,.55,.08,'square',.03)}
  else if(name==='hurt'){rpgV5Tone(190,.55,.16,'sawtooth',.045)}
  else if(name==='reward'){rpgV5Tone(620,1.7,.11,'sine',.035);setTimeout(()=>rpgV5Tone(920,1.3,.1,'sine',.03),75)}
  else if(name==='flag'){[520,660,820].forEach((n,i)=>setTimeout(()=>rpgV5Tone(n,1.05,.15,'sine',.03),i*85))}
  else if(name==='portal'){rpgV5Tone(180,3.1,.45,'sine',.045);rpgV5Noise(.32,.018,1200)}
  else if(name==='shield'){rpgV5Tone(1250,.2,.25,'sine',.04);rpgV5Noise(.24,.045,1800)}
}

function rpgV5Stage(node){return node.stageLabel||rpgStageLabel(node.id)}

rpgGameView=function(){const r=ensureRpgState(),node=rpgCurrentNode(),run=rpgEnsureRun(node,node.firstClear),map=rpgMap(node),stats=rpgComputedStats(),test=isRpgTest();return`<div class="rpg-shell map-${map.id}"><div id="rpgCanvas"></div><div class="rpg-hud"><span class="test-badge">${test?'独立测试 · 不保存':''}</span><span class="stage-chip">${rpgV5Stage(node)}</span><div class="hud-health"><i id="rpgPlayerHp" style="width:${Math.max(0,r.player.hp/stats.maxHp*100)}%"></i><b id="rpgHpLabel">${Math.ceil(r.player.hp)}/${stats.maxHp}</b></div><span>Lv.${r.player.level}</span><span>金币 <b id="rpgCoins">${r.player.coins}</b></span><span>灵魂 <b id="rpgSoulCount">${run.soulsAnswered.length}/10</b></span><span>武器 <b id="rpgWeaponName">${escapeHtml(stats.weaponItem.name)}</b></span><button onclick="rpgExitGame()">撤离</button></div><div class="weapon-switch">${r.equipment.weapons.map((id,i)=>`<button data-weapon="${i}" onclick="rpgSwitchWeapon(${i})" class="${i===r.equipment.activeWeapon?'active':''}"><span>${i+1}</span>${escapeHtml(rpgItemById(id)?.name||'空')}</button>`).join('')}</div><div class="quick-items">${r.equipment.quickItems.map((id,i)=>`<button onclick="rpgUseItem(${i})"><span>${i+4}</span>${RPG_CONSUMABLES[id]?.icon||'?'}<b>${r.consumables[id]||0}</b></button>`).join('')}</div><div class="rpg-controls"><div><button data-rpg="left">←</button><button data-rpg="right">→</button></div><div><button data-rpg="jump">跳</button><button data-rpg="dodge">闪</button><button data-rpg="attack">攻</button></div></div><div class="rotate-note"><div><strong>请把手机横过来</strong><p>横屏后才能完整操作。</p></div></div><div class="rpg-start" id="rpgStart"><div><small>${rpgV5Stage(node)} · 推荐战力 ${node.recommendedPower}</small><h2>${escapeHtml(map.name)}</h2><p>从蓝旗出发，击败馆内敌人。Boss灵魂消散后，用武器攻击终点传送门完成小关。</p><button onclick="rpgLaunch()">进入 ${rpgV5Stage(node)}</button></div></div><div id="rpgModal"></div></div>`}

rpgRouteView=function(){const r=ensureRpgState();rpgEnsureNodes(r.route.unlocked);const stats=rpgComputedStats(),nodes=r.route.nodes.slice(0,Math.min(88,r.route.unlocked+5));return shell('冒险路线','MUSEUM EXPEDITION · 88 STAGES',`<div class="course-tabs"><button onclick="showView('course')">学习章节</button><button class="active">冒险路线</button><button onclick="showView('rpgInventory')">装备工坊</button></div><div class="route-summary"><div><span>角色等级</span><strong>${r.player.level}</strong></div><div><span>当前战力</span><strong>${stats.power}</strong></div><div><span>金币</span><strong>${r.player.coins}</strong></div><div><span>艺术粉尘</span><strong>${r.player.dust}</strong></div></div><div class="rpg-route">${nodes.map((n,i)=>{const map=rpgMap(n),locked=n.id>r.route.unlocked,done=n.firstClear||n.status==='completed';return`<article class="route-node ${locked?'locked':done?'done':'current'} map-${map.id}" style="--node-accent:${map.accent};--route-shift:${i%2?1:-1}"><button ${locked?'disabled':''} onclick="rpgStartNode(${n.id},${done})"><span class="node-medal">${locked?'◆':rpgV5Stage(n)}</span><div><small>${done?'可重复挑战':n.id===r.route.unlocked?'当前小关':'未解锁'}</small><h3>${escapeHtml(map.name)}</h3><p>推荐战力 ${n.recommendedPower} · ${escapeHtml(n.lootPreview)}</p><b>${done?`${'★'.repeat(n.stars)}${'☆'.repeat(3-n.stars)}`:'进入关卡'}</b></div></button></article>`}).join('')}</div>`)}

function rpgContinueNext(id){rpgDestroy();document.getElementById('rpgModal').innerHTML='';state.view='rpgRoute';render();const r=ensureRpgState();if(id<=r.route.unlocked)rpgStartNode(id,rpgNode(id).firstClear)}
rpgShowResult=function(node,stars){const r=ensureRpgState(),next=rpgNode(node.id+1),canContinue=next&&next.id<=r.route.unlocked;const host=document.getElementById('rpgModal');if(host)host.innerHTML=`<section class="rpg-result"><small>${rpgV5Stage(node)} 完成并已存档</small><h2>${escapeHtml(node.mapName)}</h2><div>${'★'.repeat(stars)}${'☆'.repeat(3-stars)}</div><p>${canContinue?`${rpgV5Stage(next)} 已开放，可以从新入口蓝旗继续。`:'下一小关将在完成下一次三轮训练后开放。'}</p>${canContinue?`<button onclick="rpgContinueNext(${next.id})">进入 ${rpgV5Stage(next)}</button>`:''}<button onclick="rpgExitGame()">返回冒险路线</button></section>`}

class RpgSceneV5 extends RpgScene{
  preload(){super.preload();this.load.spritesheet(RPG_V5_HERO_TEXTURES.sword,'assets/art/hero-sword-v6.png',{frameWidth:256,frameHeight:256});this.load.spritesheet(RPG_V5_HERO_TEXTURES.greatsword,'assets/art/hero-greatsword-v6.png',{frameWidth:256,frameHeight:256});this.load.spritesheet(RPG_V5_HERO_TEXTURES.dual,'assets/art/hero-dual-v6.png',{frameWidth:256,frameHeight:256});this.load.spritesheet(RPG_V5_HERO_TEXTURES.bow,'assets/art/hero-bow-v6.png',{frameWidth:256,frameHeight:256})}
  create(){super.create();this.player.body.setSize(74,128).setOffset(91,98);this.player.setScale(.42);this.time.delayedCall(0,()=>this.snapPlayerToSafeSurface());this.time.delayedCall(90,()=>this.snapPlayerToSafeSurface());this.updatePortalState();this.invulnerableUntil=Date.now()+900}
  baseHeroKey(){const id=rpgComputedStats().weaponItem.baseId;return RPG_V5_HERO_TEXTURES[id]||RPG_V5_HERO_TEXTURES.sword}
  compositeHeroKey(){const r=ensureRpgState(),base=this.baseHeroKey(),ids=[r.equipment.helmet,r.equipment.chest,r.equipment.bracer,r.equipment.boots].map(id=>rpgItemById(id)?.id||'none'),key=`${base}-${ids.join('-')}`.replace(/[^a-zA-Z0-9_-]/g,'');if(this.textures.exists(key))return key;const source=this.textures.get(base).getSourceImage(),canvas=document.createElement('canvas');canvas.width=1536;canvas.height=1024;const ctx=canvas.getContext('2d');ctx.drawImage(source,0,0);/* 生成图的相邻动作有少量像素越过256格边界，运行时确定性裁掉，防止头发出现在脚下。 */const cleanBottom=[238,230,205];for(let row=0;row<cleanBottom.length;row++)for(let col=0;col<6;col++){const y=row*256+cleanBottom[row];ctx.clearRect(col*256,y,256,(row+1)*256-y)}const slots=[['helmet',r.equipment.helmet,108,48,40,22],['chest',r.equipment.chest,105,101,46,35],['bracer',r.equipment.bracer,151,121,18,18],['boots',r.equipment.boots,101,201,54,19]];for(const [,id,ox,oy,w,h] of slots){const item=rpgItemById(id);if(!item)continue;const rarity=RPG_RARITIES[item.rarityRank||0],color=rarity?.color||'#d6c39c';ctx.save();ctx.globalCompositeOperation='source-atop';ctx.globalAlpha=.32;ctx.fillStyle=color;for(let row=0;row<4;row++)for(let col=0;col<6;col++){const x=col*256+ox,y=row*256+oy;ctx.fillRect(x,y,w,h);ctx.globalAlpha=.48;ctx.fillRect(x,y,w,3);ctx.globalAlpha=.32}ctx.restore()}this.textures.addSpriteSheet(key,canvas,{frameWidth:256,frameHeight:256});return key}
  createHeroAnimations(){const texture=this.compositeHeroKey();for(const key of ['rpg-idle','rpg-run','rpg-attack'])if(this.anims.exists(key))this.anims.remove(key);const add=(key,frames,rate=8,repeat=-1)=>this.anims.create({key,frames:frames.map(frame=>({key:texture,frame})),frameRate:rate,repeat});add('rpg-idle',[0,1,2,3,4,5],5);add('rpg-run',[6,7,8,9,10,11],11);add('rpg-attack',[18,19,20],14,0);if(this.player){this.player.setTexture(texture,0);this.player.play('rpg-idle',true)}}
  refreshWeapon(){this.stats=rpgComputedStats();ensureRpgState().player.hp=Math.min(ensureRpgState().player.hp,this.stats.maxHp);if(this.weaponFx)this.weaponFx.removeAll(true);this.createHeroAnimations();rpgRenderHud()}
  surfaceBelow(x,fromBottom=0){let top=480;for(const group of [this.solids,this.platforms])for(const s of group?.getChildren?.()||[]){if(!s.body)continue;if(x>=s.body.left+4&&x<=s.body.right-4&&s.body.top>=fromBottom-8)top=Math.min(top,s.body.top)}return top}
  settlePlayerOnSurface(x=this.player?.x){if(!this.player?.body)return;this.player.body.updateFromGameObject();const top=this.surfaceBelow(x,this.player.body.bottom),delta=top-this.player.body.bottom+1;this.player.y+=delta;this.player.setVelocity(0,0);this.player.body.updateFromGameObject();this.jumpCount=0;this.forceGroundedUntil=this.time.now+240;this.player.anims.stop();this.player.setFrame(0);this.player.play('rpg-idle',true)}
  snapPlayerToSafeSurface(){if(!this.player?.body)return;const x=Math.max(90,Math.min(RPG_V5_WORLD_END-120,this.run.playerX||this.run.checkpoint?.x||120));this.player.setPosition(x,Math.min(this.run.playerY||420,420)).setVelocity(0,0);this.player.body.updateFromGameObject();this.settlePlayerOnSurface(x);this.run.playerX=Math.round(this.player.x);this.run.playerY=Math.round(this.player.y)}
  makeLayout(){const rand=rpgRandom(this.node.layoutSeed),patterns=[[390,365,210],[720,305,180],[1030,390,220],[1340,320,190],[1660,380,230],[1980,310,190],[2300,370,220],[2620,290,180],[2930,380,240],[3280,315,210],[3600,385,230]];patterns.forEach(p=>this.makePlatform(p[0]+Math.round(rand()*28),p[1]+Math.round((rand()-.5)*18),p[2]));for(const x of [1220,2760,3660])this.makeSolid(x,438,58,42);const map=this.node.mapId;if(map==='gallery')for(const x of [760,1850,3100])this.add.rectangle(x,175,145,105,0x3a1e1c,.35).setStrokeStyle(7,0xc69344).setDepth(-10);if(map==='blueprint')for(const x of [700,1900,3150])this.add.grid(x,210,250,200,25,20,0x103f59,.25,0x6ec8ef,.28).setDepth(-10);if(map==='garden')for(const x of [680,1750,3050]){this.add.circle(x,430,78,0x184a35,.35).setDepth(-8);for(let i=0;i<5;i++)this.add.circle(x-48+i*24,390-(i%2)*16,13,0x78c68d,.4).setDepth(-7)}if(map==='cathedral')for(const x of [1050,2200,3400]){const bell=this.add.triangle(x,130,0,70,35,0,70,70,0xd8ae53,.35).setDepth(-9);this.tweens.add({targets:bell,angle:{from:-10,to:10},duration:1250,yoyo:true,repeat:-1})}if(map==='modern')for(const x of [850,2050,3300]){const art=this.add.star(x,220,6,30,85,0x57d6e6,.18).setStrokeStyle(3,0xef6ec8,.35).setDepth(-8);this.tweens.add({targets:art,angle:360,duration:7000,repeat:-1})}}
  createBlocks(){this.blocks=[];const xs=[570,900,1240,1580,1920,2260,2640,2990,3330,3670];xs.forEach((x,i)=>{if(this.run.openedBlocks.includes(`q${i}`))return;const y=245+(i%3)*52,b=this.add.rectangle(x,y,48,48,0xd8b763).setStrokeStyle(4,0x68491f).setDepth(12),mark=this.add.text(x,y,'?',{font:'900 28px monospace',color:'#102331'}).setOrigin(.5).setDepth(13);this.physics.add.existing(b,true);b.blockId=`q${i}`;b.mark=mark;this.blocks.push(b);this.physics.add.overlap(this.projectiles,b,(p,block)=>{p.destroy();this.openBlock(block)})})}
  openBlock(b){if(!b?.active)return;b.active=false;if(!this.run.openedBlocks.includes(b.blockId))this.run.openedBlocks.push(b.blockId);const r=ensureRpgState(),reward=Math.abs(rpgHash(`${this.run.seed}-${b.blockId}`))%5;if(reward===0)r.player.hp=Math.min(rpgComputedStats().maxHp,r.player.hp+rpgComputedStats().maxHp*.25);if(reward===1){if(r.player.shield)r.consumables.hint++;else r.player.shield=true}if(reward===2)r.consumables.hint++;if(reward===3)r.consumables.potion++;if(reward===4)r.player.coins+=25*this.node.id;b.body.enable=false;const orb=this.add.circle(b.x,b.y,12,reward===1?0x7eeeff:0xffd76a,1).setStrokeStyle(3,0xffffff).setDepth(30);this.tweens.add({targets:orb,y:b.y-80,scale:1.7,alpha:0,duration:650,onComplete:()=>orb.destroy()});this.tweens.add({targets:[b,b.mark],scale:1.35,alpha:0,angle:22,duration:220,onComplete:()=>{b.mark?.destroy();b.destroy()}});rpgV5Sound('reward');this.syncShieldEffect();rpgRenderHud();rpgPersist()}
  createCheckpoints(){this.checkpoints=this.physics.add.staticGroup();[120,1480,2820,3840].forEach((x,i)=>{const id=`cp${i}`,active=this.run.checkpoints.includes(id),flagX=x-38,pole=this.add.rectangle(flagX,429,5,96,0x9fb9c9).setDepth(8),cloth=this.add.triangle(flagX+18,385,0,0,46,12,0,29,active?0x39bfff:0x315b82,1).setStrokeStyle(2,active?0xbcecff:0x7196b1).setDepth(9),zone=this.add.zone(x,430,84,100);this.physics.add.existing(zone,true);zone.cpId=id;zone.flag={pole,cloth,active};this.checkpoints.add(zone);this.physics.add.overlap(this.player,zone,()=>this.activateCheckpoint(zone));if(active)this.tweens.add({targets:cloth,scaleX:{from:.94,to:1.05},duration:620,yoyo:true,repeat:-1})})}
  activateCheckpoint(cp){if(cp.flag?.active)return;const r=ensureRpgState();cp.flag.active=true;if(!this.run.checkpoints.includes(cp.cpId))this.run.checkpoints.push(cp.cpId);if(this.node.id<=3)r.player.hp=Math.min(rpgComputedStats().maxHp,r.player.hp+rpgComputedStats().maxHp*.15);this.run.checkpoint={id:cp.cpId,x:cp.x,hp:r.player.hp,enemySnapshot:this.run.enemies.map(e=>({id:e.id,hp:e.hp,alive:e.alive,soulResolved:e.soulResolved}))};cp.flag.cloth.setFillStyle(0x39bfff).setStrokeStyle(2,0xd8f6ff);this.tweens.add({targets:cp.flag.cloth,scaleX:{from:.82,to:1.08},duration:240,yoyo:true,repeat:2});const flash=this.add.circle(cp.x,410,12,0x62cfff,.5).setDepth(20);this.tweens.add({targets:flash,scale:5,alpha:0,duration:520,onComplete:()=>flash.destroy()});rpgV5Sound('flag');rpgPersist();rpgRenderHud()}
  createRooms(){this.secretWalls=[];this.createSecretRoute();this.createPortal()}
  createSecretRoute(){this.makePlatform(2070,260,210);this.makePlatform(2320,210,180);const opened=this.run.openedRooms.includes('secret-route-1'),wall=this.add.rectangle(2525,179,34,118,0x5a3f36,1).setStrokeStyle(3,0xc58d66).setDepth(9);for(let i=0;i<4;i++)this.add.line(0,0,2514+i*5,140+i*17,2535-i*4,160+i*16,0xe0b28a,.8).setOrigin(0).setDepth(10);this.physics.add.existing(wall,true);wall.secretId='secret-route-1';if(opened)wall.destroy();else{this.secretWalls.push(wall);this.physics.add.overlap(this.projectiles,wall,(p,w)=>{p.destroy();this.breakSecretWall(w)})}if(!this.run.collected.includes('secret-reward')){const reward=this.add.star(2640,165,5,8,18,0xffd45f).setStrokeStyle(3,0xffffff).setDepth(13);this.physics.add.existing(reward,true);this.physics.add.overlap(this.player,reward,()=>{if(!reward.active)return;this.run.collected.push('secret-reward');ensureRpgState().consumables.hint++;reward.destroy();rpgV5Sound('reward');rpgPersist()})}}
  breakSecretWall(w){if(!w?.active)return;if(!this.run.openedRooms.includes(w.secretId))this.run.openedRooms.push(w.secretId);this.tweens.add({targets:w,alpha:0,scaleX:.2,angle:15,duration:250,onComplete:()=>w.destroy()});rpgV5Sound('heavy');rpgPersist()}
  createPortal(){const x=RPG_V5_WORLD_END-120,outer=this.add.ellipse(x,378,92,160,0x1a4168,.35).setStrokeStyle(7,0x4c6880,.75).setDepth(12),inner=this.add.ellipse(x,378,58,126,0x102331,.9).setDepth(11),rune=this.add.star(x,378,8,19,28,0x365671,.55).setDepth(13),zone=this.add.zone(x,390,120,185);this.physics.add.existing(zone,true);this.portal={x,outer,inner,rune,zone,active:false,transitioning:false};this.physics.add.overlap(this.projectiles,zone,(p)=>{p.destroy();this.tryPortalStrike('projectile')});this.tweens.add({targets:rune,angle:360,duration:6500,repeat:-1});this.updatePortalState()}
  updatePortalState(){if(!this.portal)return;const boss=this.run.enemies.find(e=>e.id==='boss'),active=Boolean(boss&&!boss.alive&&boss.soulResolved);if(active&&!this.portal.active){this.portal.active=true;this.portal.outer.setStrokeStyle(7,0x72eaff,1);this.portal.inner.setFillStyle(0x266d90,.78);this.portal.rune.setFillStyle(0xb7f8ff,.9);this.tweens.add({targets:[this.portal.outer,this.portal.inner],scale:{from:.96,to:1.06},alpha:{from:.65,to:1},duration:820,yoyo:true,repeat:-1});this.floatText(this.portal.x,270,'传送门已开启 · 用武器攻击',0x9ff8ff);rpgV5Sound('portal')}}
  tryPortalStrike(source='melee'){if(!this.portal?.active||this.portal.transitioning)return false;if(source!=='projectile'&&Math.abs(this.player.x-this.portal.x)>230)return false;this.portal.transitioning=true;rpgV5Sound('portal');this.cameras.main.fadeOut(430,20,42,62);this.time.delayedCall(440,()=>this.completeV5Run());return true}
  completeV5Run(){const completedId=this.node.id;super.completeRun();const r=ensureRpgState(),next=rpgNode(completedId+1);if(next&&next.id<=r.route.unlocked&&next.status==='locked'){next.status='available';next.sourceDate='portal';rpgPersist()}}
  tryWorldInteractions(){for(const b of this.blocks||[])if(b.active&&Math.abs(this.player.x-b.x)<105&&Math.abs(this.player.y-b.y)<135)this.openBlock(b);for(const w of this.secretWalls||[])if(w.active&&Math.abs(this.player.x-w.x)<120&&Math.abs(this.player.y-w.y)<145)this.breakSecretWall(w);this.tryPortalStrike('melee')}
  attack(time){const before=this.lastAttack;super.attack(time);if(this.lastAttack===before)return;const w=rpgComputedStats().weapon;rpgV5Sound(w===RPG_WEAPONS.greatsword?'heavy':w===RPG_WEAPONS.bow?'arrow':'swing');this.tryWorldInteractions()}
  hitEnemy(e,multiplier,fromX){const hp=e?.dataRef?.hp;super.hitEnemy(e,multiplier,fromX);if(e?.dataRef?.hp<hp)rpgV5Sound('hit')}
  damagePlayer(amount,fromX){const hp=ensureRpgState().player.hp,shield=ensureRpgState().player.shield;super.damagePlayer(amount,fromX);if(ensureRpgState().player.hp<hp)rpgV5Sound('hurt');else if(shield&&!ensureRpgState().player.shield)rpgV5Sound('shield')}
  finishEnemy(ref,soul){if(ref.id!=='boss')super.finishEnemy(ref,soul);else{ref.alive=false;ref.soulResolved=soul||ref.soulResolved;const loot=rpgRollMonsterLoot(ref,this.run);rpgAddRunReward(loot);this.showLoot(ref,loot);this.updatePortalState();rpgRenderHud();rpgPersist()}this.time.delayedCall(40,()=>this.settlePlayerOnSurface())}
  syncShieldEffect(){const active=ensureRpgState().player.shield;if(active&&!this.shieldFx){const veil=this.add.graphics();veil.lineStyle(3,0x9eefff,.7);veil.fillStyle(0x5ad7ff,.045);veil.fillRoundedRect(-39,-59,78,118,30);veil.strokeRoundedRect(-39,-59,78,118,30);for(let i=0;i<5;i++)veil.lineBetween(-30+i*15,-52,-37+i*15,-40);const dotA=this.add.circle(0,0,1,0xffffff,0),dotB=this.add.circle(0,0,1,0xffffff,0);this.shieldFx=this.add.container(this.player.x,this.player.y,[veil,dotA,dotB]).setDepth(28);this.shieldRing=veil;this.shieldDots=[dotA,dotB];this.tweens.add({targets:veil,alpha:{from:.35,to:.8},duration:1100,yoyo:true,repeat:-1})}if(!active&&this.shieldFx){this.shieldFx.destroy(true);this.shieldFx=null;this.shieldDots=null;this.shieldRing=null}}
  breakShield(){const shards=[];for(let i=0;i<14;i++){const a=Math.PI*2*i/14,p=this.add.triangle(this.player.x,this.player.y,0,0,7,3,1,9,0xaff7ff,.9).setDepth(31);shards.push(p);this.tweens.add({targets:p,x:p.x+Math.cos(a)*85,y:p.y+Math.sin(a)*110,angle:220,alpha:0,duration:420,onComplete:()=>p.destroy()})}const wave=this.add.ellipse(this.player.x,this.player.y,76,112,0x6ae7ff,.06).setStrokeStyle(4,0xe7ffff).setDepth(30);this.tweens.add({targets:wave,scale:1.8,alpha:0,duration:380,onComplete:()=>wave.destroy()});rpgV5Sound('shield');this.time.delayedCall(40,()=>this.syncShieldEffect())}
  failToCheckpoint(){super.failToCheckpoint();this.time.delayedCall(30,()=>this.snapPlayerToSafeSurface())}
  update(time,delta){super.update(time,delta);if(!this.player?.body||this.soulBattle)return;this.updatePortalState();const top=this.surfaceBelow(this.player.x,this.player.body.bottom),resting=Math.abs(this.player.body.bottom-top)<=3&&Math.abs(this.player.body.velocity.y)<18;if((time<this.forceGroundedUntil||resting)&&time-this.lastAttack>260){this.jumpCount=0;if(Math.abs(this.player.body.velocity.x)<12&&(!this.player.anims.isPlaying||this.player.anims.currentAnim?.key!=='rpg-idle'))this.player.play('rpg-idle',true)}}
}

rpgLaunch=function(){if(isRpgTest()&&!rpgTestBackup)rpgTestBackup=JSON.stringify(state.rpg);const node=rpgCurrentNode();rpgEnsureRun(node,node.firstClear);document.getElementById('rpgStart')?.remove();rpgDestroy();const config={type:Phaser.AUTO,parent:'rpgCanvas',width:RPG_VIEW_W,height:RPG_VIEW_H,backgroundColor:'#091522',pixelArt:true,physics:{default:'arcade',arcade:{gravity:{y:920},debug:false}},scene:[RpgSceneV5]};rpgInstance=new Phaser.Game(config)}

window.__RPG_V5__={version:6,stage:()=>rpgV5Stage(rpgCurrentNode()),hero:()=>rpgScene?.player?.texture?.key,portal:()=>Boolean(rpgScene?.portal?.active),openBlock:()=>{const b=rpgScene?.blocks?.find(x=>x.active);if(b)rpgScene.openBlock(b)},snap:()=>rpgScene?.snapPlayerToSafeSurface(),portalStrike:(source='melee')=>rpgScene?.tryPortalStrike(source)};
